/* eslint-disable max-lines */
export const classes: string[][] = [
  ['aba', 'base', 'declive', 'encosta', 'falda', 'flanco', 'ilharga', 'ladeira', 'lado', 'orla', 'sopé', 'vertente'],
  [
    'abas',
    'adjacências',
    'bairros',
    'cercanias',
    'circunvizinhanças',
    'confins',
    'contiguidades',
    'contornos',
    'imediações',
    'proximidades',
  ],
  ['abafar', 'conter', 'reprimir', 'sofrear', 'sufocar'],
  ['abafar', 'abrigar', 'agasalhar', 'cobrir', 'resguardar', 'tapar'],
  ['abafar', 'acoitar', 'atabafar', 'encobrir', 'esconder', 'ocultar', 'receptar', 'reter', 'sonegar'],
  ['abafeira', 'charco', 'lamaçal', 'pântano'],
  ['abaixar', 'abater', 'arriar', 'baixar', 'descer'],
  ['abaixar', 'abater', 'aviltar', 'degradar', 'rebaixar'],
  ['abalançar-se', 'afoitar-se', 'atrever-se'],
  ['abalar', 'azular', 'esgueirar-', 'fugir', 'partir'],
  ['abalar', 'demover', 'dissuadir'],
  ['abalizado', 'assinalado', 'distinto', 'notável'],
  ['abalo', 'agitação', 'comoção', 'convulsão', 'estremecimento', 'terremoto', 'tremor de terra', 'trepidação'],
  ['abalroar', 'aferrar', 'atracar', 'investir'],
  ['abandonar', 'desprezar', 'desproteger'],
  ['abandono', 'desafetação', 'naturalidade'],
  [
    'abaratar',
    'baratear',
    'depreciar',
    'desapreciar',
    'desencarecer',
    'desestimar',
    'embaratecer',
    'malbaratar',
    'menoscabar',
    'menosprezar',
  ],
  ['abantesma', 'espetro', 'fantasma', 'larva'],
  ['abarcar', 'açambarcar', 'monopolizar'],
  ['abarcar', 'abranger', 'compreender'],
  [
    'abarroado',
    'cabeçudo',
    'caprichoso',
    'contumaz',
    'encaprichado',
    'insistente',
    'obstinado',
    'opiniático',
    'pertinaz',
    'teimoso',
    'tenaz',
  ],
  [
    'abastado',
    'apatacado',
    'argentário',
    'banqueiro',
    'capitalista',
    'endinheirado',
    'milionário',
    'opulento',
    'remediado',
    'ricaço',
    'rico',
  ],
  ['abastardar', 'degenerar', 'desfigurar'],
  [
    'abastar',
    'abastecer',
    'aprovisionar',
    'fornecer',
    'fornir',
    'ministrar',
    'municiar',
    'municionar',
    'munir',
    'prover',
    'subministrar',
  ],
  ['abater', 'aluir', 'cair', 'desabar', 'desmoronar'],
  ['abater', 'deitar abaixo', 'demolir', 'derribar'],
  ['abater', 'deminuir', 'descontar', 'minuir'],
  ['abatimento', 'depressão', 'languidez'],
  [
    'abandonar',
    'abdicar',
    'ceder',
    'demitir-se',
    'desistir',
    'desobrigar-se',
    'exonerar-se',
    'largar',
    'recusar',
    'rejeitar',
    'renunciar',
    'resignar',
  ],
  ['abdômen', 'barriga', 'entranha', 'ventre'],
  ['abençoar', 'bendizer', 'benzer', 'louvar'],
  ['abertura', 'fresta', 'greta', 'racha', 'resquício'],
  ['abelhudo', 'entremetido', 'introduzido', 'intrometido', 'intruso', 'metediço', 'oferecido'],
  ['aberto', 'amplo', 'espaçoso', 'largo', 'vasto'],
  ['aberração', 'absurdo', 'contrassenso', 'despropósito', 'desrazão', 'destampatório'],
  ['abestalhado', 'abobado', 'aparvalhado'],
  ['abeirar-se', 'apropinquar-', 'aproximar-se'],
  ['abespinhar-se', 'irritar-se', 'zangar-se'],
  ['abicar', 'abordar', 'ancorar', 'aportar', 'arribar', 'atracar', 'chegar', 'fundear', 'surgir', 'varar'],
  ['abismo5', 'báratro', 'despenhadeiro', 'pego', 'precipício', 'rodomoinho', 'sorvedouro', 'tragadoiro', 'voragem'],
  ['abjeto', 'desprezível', 'detestável', 'ignóbil'],
  ['abjurar', 'abrenunciar', 'apostatar', 'converter-se', 'desprofessar', 'renegar', 'renunciar', 'trair'],
  ['ablação', 'amputação'],
  ['abnegação', 'altruísmo', 'desambição', 'desamor', 'desapego', 'desinteresse', 'desprendimento'],
  ['abluir', 'apurar', 'lavar', 'limpar', 'purificar'],
  ['ab-rogar', 'abolir', 'derrogar', 'extinguir'],
  ['abonação', 'abono', 'arras', 'caução', 'fiança', 'garantia', 'hipoteca', 'penhor', 'segurança', 'sinal'],
  ['aborígene', 'autóctone', 'indígena', 'nativo', 'natural', 'originário', 'íncola'],
  ['abortar', 'frustrar-se', 'gorar', 'malograr-se'],
  ['abra', 'angra', 'enseada', 'golfo', 'recôncavo'],
  ['abonançar', 'abrandar', 'adoçar', 'apaziguar', 'enternecer', 'moderar', 'serenar', 'suavizar'],
  [
    'abrasador',
    'abrasante',
    'ardente',
    'caloroso',
    'candente',
    'carbonizante',
    'comburente',
    'cálido',
    'cáustico',
    'queimante',
    'queimoso',
    'quente',
  ],
  ['abrasar-se6'],
  ['abreviar', 'encurtar', 'reduzir', 'restringir'],
  ['abrigo', 'amparo', 'asilo', 'coito', 'esconderijo', 'guarida', 'homizio', 'refúgio', 'valhacoito'],
  ['abrir', 'descerrar', 'entreabrir', 'escancarar', 'soabrir'],
  ['abrir', 'desligar', 'desunir', 'separar', 'soltar'],
  ['abrolhos', 'alfaques', 'baixios', 'baixos', 'cachopos', 'escolhos', 'farelhões', 'recifes'],
  ['abrupto', 'alcantilado', 'aprumado', 'empinado', 'escarpado', 'ladeirento', 'íngreme'],
  ['absconso', 'abscôndito', 'clandestino', 'escondido', 'oculto', 'recôndito', 'retruso', 'secreto'],
  ['absolutismo', 'autocracia', 'despotismo'],
  ['absoluto', 'arrogante', 'categórico', 'decisivo', 'definitivo', 'imperativo', 'imperioso'],
  ['absolver', 'anistiar', 'perdoar', 'remitir'],
  [
    'desafinado',
    'desarmônico',
    'desentoado',
    'destemperado',
    'destoante',
    'discordante',
    'discrepante',
    'dissonante',
    'malsoante',
    'ábsono',
  ],
  [
    'absorver',
    'aspirar',
    'beber',
    'chuchar',
    'chupar',
    'comer',
    'consumar',
    'consumir',
    'deglutir',
    'devorar',
    'engolir',
    'sorver',
    'sugar',
    'tragar',
  ],
  ['absorto', 'admirado', 'assombrado', 'enlevado', 'extasiado', 'maravilhado', 'pensativo'],
  ['abster-se', 'abstinência', 'privar-se', 'privação'],
  ['absterso', 'alvo', 'brilhante', 'polido', 'terso'],
  ['abstinente', 'abstêmio', 'frugal', 'sóbrio'],
  ['abstrato', 'abstruso'],
  ['abundância', 'fartura', 'opulência', 'riqueza'],
  [
    'abusão',
    'crendice',
    'fanatismo',
    'patranha',
    'peta',
    'preconceito',
    'prejuízo',
    'preocupação',
    'prevenção',
    'superstição',
  ],
  ['acabar', 'cessar', 'concluir', 'descontinuar'],
  ['acabar', 'falecer', 'fenecer', 'morrer', 'perecer'],
  [
    'abatido',
    'acabado',
    'alquebrado',
    'avelhentado',
    'consumido',
    'desfigurado',
    'envelhecido',
    'gasto',
    'idoso',
    'macerado',
    'quebrado',
    'velho',
  ],
  ['acabado', 'completo', 'magistral', 'perfeito'],
  [
    'aborrecer',
    'acabrunhar',
    'afligir',
    'amofinar',
    'apoquentar',
    'contristar',
    'desgostar',
    'entristecer',
    'humilhar',
    'importunar',
    'magoar',
    'molestar',
    'mortificar',
    'oprimir',
    'vexar',
  ],
  ['academia', 'colégio', 'escola', 'ginásio', 'instituto', 'liceu', 'universidade'],
  ['acalentar', 'agradar', 'amimar', 'consolar'],
  ['acampamento', 'arraial', 'bivaque'],
  [
    'acanhado',
    'acanhamento',
    'apoucado',
    'modesto',
    'modéstia',
    'pudibundo',
    'pudico',
    'timidez',
    'tímido',
    'vergonha',
    'vergonhoso',
  ],
  ['ato', 'ação', 'fato'],
  ['ação', 'batalha', 'combate', 'peleja', 'pugna'],
  ['ação', 'demanda', 'litígio', 'pleito', 'processo'],
  ['acaso', 'fado', 'fadário', 'fortuna', 'sina', 'sorte'],
  ['acaso', 'por acaso', 'porventura'],
  ['acatamento', 'acatar', 'respeitar', 'respeito'],
  ['acautelado', 'avisado', 'cauteloso', 'cauto', 'precatado', 'precavido', 'prevenido'],
  ['acepção', 'sentido', 'significação'],
  ['aceder', 'aderir', 'anuir', 'aquiescer', 'concordar', 'condescender', 'conformar-', 'consentir'],
  ['aceitar', 'receber', 'tomar', 'recebi', 'resgatar'],
  ['acelerar', 'aligeirar', 'apressar', 'apressurar', 'ativar', 'precipitar'],
  ['acento', 'diapasão', 'som', 'sonido', 'soído', 'timbre', 'toada', 'tom'],
  ['acento', 'pronúncia'],
  ['acerbo', 'acre', 'acérrimo', 'azedo', 'ácido'],
  ['acerca de'],
  ['acertar', 'adivinhar', 'atinar'],
  ['acervo', 'monte', 'montão', 'pilha', 'ruma'],
  ['acessório', 'contingente', 'secundário'],
  ['achado', 'descoberta', 'invento', 'invenção'],
  ['achar', 'deparar', 'descobrir', 'encontrar', 'inventar'],
  ['achaque', 'doença', 'enfermidade', 'incômodo', 'incômodos', 'indisposição', 'moléstia'],
  [
    'acidental',
    'aleatório',
    'casual',
    'contingente',
    'eventual',
    'fortuito',
    'imprevisto',
    'incerto',
    'inesperado',
    'inopinado',
    'ocasional',
  ],
  ['acidente', 'catástrofe', 'desastre', 'desgraça'],
  ['aclamar', 'aplaudir', 'proclamar', 'vitoriar'],
  ['aclarar', 'elucidar', 'esclarecer', 'ilustrar'],
  ['acobardar', 'amedrontar', 'intimidar'],
  ['ações', 'fatos', 'façanhas', 'feitos', 'proezas'],
  ['acoitar-se', 'acoitar', 'asilar-se', 'asilar', 'esconder-se', 'esconder', 'ocultar-se', 'ocultar'],
  ['açoitar', 'chicotar', 'verdascar', 'vergastar'],
  ['acomodar', 'adaptar', 'adequar', 'ajustar'],
  ['acompanhar', 'comboiar', 'escoltar', 'seguir'],
  ['aconselhar', 'guiar', 'insinuar', 'sugerir'],
  ['acontecer', 'dar-se', 'ocorrer', 'suceder'],
  ['acordar', 'ajustar', 'assentar', 'combinar', 'concertar', 'concordar', 'convencionar', 'convir'],
  ['acordar', 'despertar'],
  ['acoroçoar', 'alentar', 'animar', 'induzir'],
  ['acorrentar', 'enca dear', 'encorrentar'],
  ['acorrer', 'acudir', 'afluir'],
  ['acossar', 'perseguir'],
  ['acostumar-se', 'dar-se', 'habituar-se'],
  ['acrescentar', 'acrescer', 'aumentar'],
  ['acrescentar', 'adicionar', 'adir', 'aditar', 'agregar', 'ajuntar', 'juntar'],
  ['acreditar', 'crer'],
  ['acro', 'frágil', 'quebradiço'],
  ['acudir', 'amparar', 'auxiliar', 'socorrer'],
  ['acusar', 'delatar', 'denunciar', 'malsinar'],
  ['acusar', 'arguir', 'criminar', 'culpar', 'incriminar', 'inculpar'],
  [
    'adágio',
    'aforismo',
    'anexim',
    'axioma',
    'brocardo',
    'ditado',
    'dito',
    'máxima',
    'paremia',
    'preceito',
    'princípio',
    'provérbio',
    'rifão',
    'sentença',
  ],
  ['adarga', 'broquel', 'escudo', 'pavês', 'rodela'],
  ['adição', 'soma', 'total'],
  ['adiantar', 'antecipar'],
  ['adiantar-se', 'progredir', 'prosperar'],
  ['adepto', 'iniciado', 'sectarista', 'sectário'],
  ['adereçar', 'adornar', 'ataviar', 'embelecer', 'embelezar', 'enfeitar', 'ornamentar', 'ornar'],
  ['adestrar', 'ensinar', 'exercitar', 'instruir'],
  ['adiar', 'aprazar', 'demorar', 'diferir', 'dilatar', 'protelar', 'remanchar', 'retardar', 'transferir'],
  ['adivinhar', 'agoirar', 'profetizar', 'vaticinar'],
  ['adivinho', 'astrólogo', 'bruxo', 'feiticeiro', 'mandingueiro', 'mágico', 'quiromante'],
  ['adjacente', 'contíguo', 'próximo', 'vizinho'],
  ['adjetivo', 'epíteto'],
  ['adido', 'adjunto'],
  ['adjurar', 'conjurar', 'esconjurar', 'exorcizar'],
  ['admiração', 'assombro', 'espanto', 'pasmo'],
  ['admirar', 'apreciar', 'considerar', 'contemplar', 'encarar', 'examinar', 'fitar', 'olhar', 'ver'],
  ['admirável15'],
  ['admitir', 'receber'],
  ['admitir', 'consentir', 'permitir', 'tolerar'],
  ['aconselhar', 'admoestar', 'advertir', 'arguir', 'avisar', 'censurar', 'repreender', 'verberar'],
  ['adoecer', 'enfermar'],
  ['adolescência', 'juventude', 'mocidade'],
  [
    'acatamento',
    'acatar',
    'adorar',
    'adoração',
    'homenagem',
    'honra',
    'honrar',
    'respeito',
    'reverenciar',
    'reverência',
    'venerar',
    'veneração',
  ],
  ['aduana', 'aduaneiro', 'alfandegário', 'alfândega'],
  ['adubar', 'adubo', 'condimentar', 'temperar'],
  ['adular', 'bajular', 'lisonjear', 'louvaminhar'],
  ['adulterar', 'contrafazer', 'falsificar', 'imitar'],
  ['adunar', 'aunar', 'coadunar', 'reunir', 'unir'],
  ['adunco', 'arcado', 'arqueado', 'curvo', 'recurvado'],
  ['aduzir', 'alegar'],
  ['adventício', 'alienígena', 'estrangeiro', 'forasteiro', 'ádvena'],
  ['adversário', 'antagonista', 'rival', 'êmulo'],
  ['adverso', 'contrário', 'desfavorável', 'oposto'],
  ['adversa', 'adversidade', 'desdita', 'desgraça', 'fortuna', 'infelicidade', 'sorte adversa'],
  ['advocacia', 'advocatura'],
  ['advogado', 'causídico', 'defensor', 'jurisconsulto', 'jurista', 'legista', 'letrado', 'rábula'],
  ['advogado', 'defensor', 'intercessor', 'padroeiro', 'patrocinador', 'patrono', 'protetor'],
  ['afabilidade', 'agrado', 'amabilidade', 'civilidade', 'cortesia', 'polidez', 'urbanidade'],
  ['afasia', 'afonia', 'afásico', 'afônico', 'mudez'],
  [
    'afadigamento',
    'aforçuramento',
    'afã',
    'azáfama',
    'fadiga',
    'faina',
    'labor',
    'laboração',
    'labuta',
    'labutação',
    'lavor',
    'lida',
    'luta',
    'trabalho',
  ],
  ['afastar', 'apartar', 'arredar', 'descaminhar', 'desencaminhar', 'deslocar', 'desviar', 'retirar', 'separar'],
  ['aferro', 'apego'],
  ['aferrolhar', 'fechar', 'ferrolho', 'trancar'],
  ['afeição', 'afeto', 'amor', 'inclinação', 'paixão'],
  ['afetação', 'aparência', 'contrafação', 'disfarce', 'dissimulação', 'fingimento', 'simulação'],
  ['afetivo', 'afetuoso'],
  ['afetos', 'paixões'],
  ['afetuoso', 'apaixonado'],
  ['aferventar', 'aquentar', 'cozer', 'ferver'],
  ['afinidade', 'analogia', 'conexão', 'relação'],
  ['aderência', 'adesão', 'afinidade', 'atração', 'coerência', 'coesão', 'gravidade', 'gravitação', 'inerência'],
  ['afim', 'afinidade', 'agnação', 'cognato', 'cognação', 'consanguinidade', 'ágnato'],
  [
    'afirmar',
    'assegurar',
    'asseverar',
    'atestar',
    'certificar',
    'comprovar',
    'confirmar',
    'corroborar',
    'demonstrar',
    'dizer',
    'garantir',
    'ratificar',
  ],
  [
    'afixar',
    'aplicar',
    'apor',
    'atar',
    'chumbar',
    'colar',
    'fixar',
    'grudar',
    'ligar',
    'pegar',
    'pregar',
    'prender',
    'segurar',
    'sobrepor',
    'soldar',
  ],
  ['aflição', 'desgosto', 'espanhol', 'mágoa', 'pesadumbre', 'pesadume', 'pesar', 'tristeza'],
  ['afluência', 'concorrência', 'concurso'],
  ['afora', 'exceto'],
  ['afiado', 'agudo', 'aguçado', 'amolado', 'cortante', 'incisivo', 'talhante'],
  [
    'afoito',
    'animoso',
    'arrebatado',
    'arriscado',
    'arrojado',
    'atrevido',
    'audacioso',
    'audaz',
    'bravo',
    'confiado',
    'corajoso',
    'decidido',
    'desafrontado',
    'destemido',
    'determinado',
    'heroico',
    'impertérrito',
    'imponderado',
    'impávido',
    'inconsiderado',
    'intemente',
    'intrépido',
    'ousado',
    'resoluto',
    'temerário',
    'valente',
    'valoroso',
  ],
  ['afronta', 'agravo', 'injúria', 'ofensa', 'ultraje'],
  ['afrontar', 'arrostar', 'encarar'],
  ['brequefeste', 'bródio', 'comezaina', 'janta', 'patuscada', 'pândega', 'rega-bofe', 'ágape'],
  ['agonizar', 'estertorar'],
  ['agradecido', 'cativo', 'grato', 'obrigado', 'penhorado', 'reconhecido'],
  ['agreste', 'campesino', 'campestre', 'rústico'],
  ['agrário', 'agrícola', 'rural', 'rústico'],
  ['agricultor', 'agricultura', 'agronomia'],
  ['aguardar', 'esperar'],
  ['aguar', 'banhar', 'irrigar', 'molhar', 'regar'],
  ['agudeza', 'agudo', 'penetrante', 'penetração', 'perspicaz', 'perspicácia', 'sagacidade'],
  ['aguentar', 'suspender', 'sustentar', 'suster'],
  ['aio', 'amo', 'instrutor', 'mestre', 'preceptor'],
  ['airosidade', 'airoso', 'nobre', 'nobreza'],
  ['agilidade', 'destreza', 'destro', 'expedito', 'expediência', 'lesto', 'ligeireza', 'ligeiro', 'lépido', 'ágil'],
  ['agiota', 'onzeneiro', 'onzenário', 'usurário'],
  ['agitação', 'insurreição', 'rebelião', 'revolta'],
  ['agitar', 'aventar', 'controverter', 'debater', 'discutir', 'disputar', 'tratar', 'ventilar'],
  ['ajuizado', 'assisado', 'cordato', 'grave', 'judicioso', 'prudente', 'sensato', 'sisudo', 'sábio'],
  ['ala', 'fila', 'fileira', 'linha', 'renque', 'série'],
  ['alarde', 'alardear', 'jactar-se', 'jactância', 'ostentar', 'ostentação', 'vangloriar-se'],
  ['alargar', 'ampliar', 'dilatar'],
  ['alarido', 'algazarra', 'berreiro', 'bramido', 'celeuma', 'clamor', 'gritaria', 'tumulto', 'vozeria'],
  ['alarme', 'chamada', 'chamamento', 'rebate'],
  ['alarme', 'medo', 'susto', 'temor', 'terror'],
  ['albergaria', 'albergue', 'estalagem', 'guarida', 'hospedaria', 'hotel', 'pensão', 'pousada'],
  ['albescente', 'alvacento', 'alvadio', 'esbranquiçado'],
  ['alcácer', 'alcáçar', 'palácio', 'paço'],
  ['alcançar', 'conseguir', 'gozar', 'impetrar', 'lograr', 'obter'],
  ['alcançar', 'atingir', 'chegar', 'tocar'],
  ['alcance', 'desfalque', 'irregularidade'],
  ['alcantil', 'despenhadeiro', 'ribanceira'],
  ['alçar', 'elevar', 'erguer', 'levantar'],
  ['alcateia', 'bando', 'enxame', 'multidão'],
  ['alcatifa', 'alfombra', 'tapete', 'tapeçaria'],
  ['alcoice', 'bordel', 'lupanar', 'prostíbulo'],
  ['alcunha', 'apelido', 'nome', 'sobrenome'],
  ['alegar', 'citar'],
  ['alacridade', 'alegria', 'contentamento', 'exultação', 'jovialidade', 'júbilo', 'ledice', 'regozijo'],
  ['aleive', 'aleivosia', 'aleivoso', 'caluniador', 'calunioso', 'calúnia', 'traiçoeiro', 'traição'],
  ['adiante', 'além', 'após', 'depois'],
  ['alentado', 'forte', 'robusto', 'vigoroso'],
  ['alfanje', 'chanfalho', 'cimitarra', 'durindana', 'espada', 'gládio', 'montante', 'sabre', 'terçado'],
  ['afinal', 'alfim', 'enfim', 'finalmente', 'por'],
  ['algoz', 'carnífice', 'carrasco', 'executor', 'sacrificador', 'verdugo'],
  ['alguns', 'certos'],
  ['alheio', 'de outrem', 'estranho'],
  ['algures', 'alhures'],
  ['acolá', 'ali', 'além', 'aí', 'lá'],
  ['aliança', 'coalizão', 'confederação', 'liga'],
  ['aliança', 'casamento', 'consórcio', 'união'],
  ['alicerce', 'base', 'embasamento', 'fundamento', 'peanha', 'pedestal'],
  ['aliciar', 'corromper', 'engodar', 'peitar', 'seduzir', 'subornar'],
  ['alienar', 'cambiar', 'escambiar', 'permutar', 'traficar', 'trocar', 'vender'],
  ['alimentar', 'manter', 'nutrir', 'sustentar'],
  ['alimpa', 'monda', 'poda'],
  ['alistar', 'arrolar', 'catalogar', 'relacionar'],
  [
    'alcofa',
    'alforje',
    'aljava',
    'açafate',
    'bolsa',
    'bruaca',
    'carcás',
    'cesta',
    'estojo',
    'guaiaca',
    'mala',
    'mochila',
    'peçuelo',
    'picoá',
    'saco',
    'seira',
    'seirão',
  ],
  ['frio', 'frígido', 'gelado', 'glacial', 'gélido', 'regelado', 'álgido'],
  ['alma', 'coração', 'espírito', 'eu', 'ânimo'],
  [
    'almanaque',
    'anuário',
    'calendário',
    'folhinha',
    'guia',
    'indicador',
    'manual',
    'prontuário',
    'repertório',
    'roteiro',
    'vademeco',
  ],
  ['almejar', 'ambicionar', 'aspirar', 'desejar'],
  ['almo', 'criador', 'nutriente', 'nutritivo'],
  [
    'alocução',
    'arenga',
    'arrazoamento',
    'discurso',
    'fala',
    'falar',
    'fale',
    'homilia',
    'oração',
    'panegírico',
    'proclamação',
    'prática',
    'prédica',
    'sermão',
  ],
  ['adro', 'alpendrada', 'alpendre', 'pórtico', 'telheiro', 'vestíbulo', 'átrio'],
  ['altaneria', 'altivez', 'empáfia', 'fatuidade', 'impostura', 'orgulho', 'soberba', 'sobranceria'],
  ['alternativa', 'dilema', 'disjuntiva'],
  ['altitude', 'altura'],
  ['alteza', 'altura'],
  ['alterar', 'modificar', 'mudar', 'reformar', 'remodelar', 'renovar', 'transformar', 'variar'],
  ['alucinar', 'cegar', 'confundir', 'ofuscar'],
  [
    'alucinado',
    'atordoado',
    'aturdido',
    'cego',
    'delirante',
    'demente',
    'desvairado',
    'doido',
    'estonteado',
    'insano',
    'insensato',
    'louco',
    'perdido',
  ],
  ['aludir', 'enunciar', 'expor', 'indicar', 'mencionar', 'referir'],
  ['alusivo', 'concernente', 'referente', 'relativo', 'respetivo'],
  ['alquilar', 'alugar', 'arrendar', 'locar', 'sublocar'],
  ['aluno', 'discípulo', 'educando'],
  ['albor', 'alva', 'alvor', 'alvorada', 'aurora', 'crepúsculo', 'dilúculo', 'madrugada'],
  ['alvo', 'escopo', 'fim', 'fito', 'intento', 'intenção', 'mira', 'objeto', 'propósito'],
  ['centro', 'cerne', 'imo', 'interior', 'meio', 'profundeza', 'recesso', 'seio', 'âmago', 'íntimo'],
  ['abater', 'abrandar', 'acalmar', 'afrouxar', 'amainar', 'diminuir', 'enfraquecer', 'sossegar'],
  ['amansar', 'domar', 'domesticar'],
  ['amante', 'amásia', 'barregã', 'concubina'],
  ['amachucar', 'amarfanhar', 'amarrotar', 'amassar', 'enrugar', 'machucar', 'marlotar'],
  ['ambição', 'avareza', 'avidez', 'cobiça', 'cupidez', 'gana', 'ganância'],
  ['ambíguo', 'anfibológico', 'confuso', 'duvidoso', 'dúbio', 'equívoco', 'impreciso', 'incerto'],
  ['recinto', 'área', 'âmbito'],
  ['ambos', 'os dois', 'outro', 'um'],
  ['ambulante', 'errante', 'nômade', 'perdido', 'peregrino', 'teatino', 'vagabundo', 'vagante'],
  ['ameaçar', 'amedrontar', 'assustar', 'atemorizar', 'intimidar'],
  ['agradável', 'ameno', 'aprazível', 'delicioso'],
  ['abolar', 'amassar', 'amolgar', 'amossar'],
  ['acumular', 'ajuntar', 'amontoar', 'reunir'],
  ['amostra', 'indício', 'mostra', 'prova', 'sinal'],
  ['amplidão', 'amplitude', 'extensão', 'grandeza', 'imensidade', 'imensidão', 'vastidão'],
  ['anacoreta', 'cenobita', 'eremita', 'solitário'],
  ['análise', 'epítome', 'extrato', 'resumo'],
  [
    'anarquia',
    'balbúrdia',
    'caos',
    'cizânia',
    'confusão',
    'desconcerto',
    'desgoverno',
    'desordem',
    'desregramento',
    'discórdia',
  ],
  ['amaldiçoar', 'anatematizar', 'anátema', 'excomungar', 'excomunhão', 'maldição'],
  ['anatomia', 'autópsia', 'dissecção'],
  ['ancião', 'velho'],
  ['ansiedade', 'ânsia'],
  ['andaço', 'contágio', 'endemia', 'epidemia'],
  ['andar', 'caminhar', 'ir', 'marchar', 'seguir'],
  ['andrajos', 'farrapos', 'molambos', 'trapos'],
  ['anexado', 'anexar', 'anexação', 'anexo', 'incorporado', 'incorporar', 'incorporação'],
  ['anexo', 'dependente', 'unido'],
  ['aliciar', 'angariar', 'recrutar'],
  ['angu', 'mexido', 'mingau', 'pirão', 'revirado'],
  ['anelo', 'anseio', 'aspiração', 'desejo', 'vontade'],
  ['anoitecer', 'enoitecer'],
  ['anomalia', 'anormal', 'anormalidade', 'anômalo', 'excepcional', 'excepcionalidade'],
  ['anoso', 'antigo', 'idoso', 'secular', 'velho'],
  ['anotar', 'anotações', 'comentar', 'notas'],
  ['anuviar', 'carregar', 'ensombrar', 'escurecer', 'nublar', 'obcecar', 'obscurecer', 'toldar'],
  ['antártico', 'austral', 'meridional'],
  ['antecedente', 'anterior', 'precedente'],
  ['antecedentes', 'precedentes'],
  ['antecessor', 'predecessor'],
  ['antecessores', 'antepassados', 'antigos', 'ascendentes', 'avoengos', 'avós', 'maiores', 'pais'],
  ['adiantadamente', 'antecipadamente'],
  ['antemural', 'muralha', 'muro'],
  ['antipatia', 'aversão', 'repugnância', 'ódio'],
  ['antiquado', 'arcaico', 'desusado', 'obsoleto'],
  ['antiquário', 'arqueólogo'],
  ['antilogia', 'antinomia', 'antífrase', 'antítese', 'contradição', 'contrariedade', 'contraste'],
  ['antro', 'caverna', 'cova', 'furna', 'gruta', 'lapa'],
  ['aparato', 'aparelho', 'apresto', 'preparativo'],
  [
    'alardo',
    'aparato',
    'esplendor',
    'fausto',
    'grandeza',
    'luxo',
    'magnificência',
    'majestade',
    'ostentação',
    'pompa',
    'sumptuosidade',
  ],
  ['aparecimento', 'aparição'],
  ['aparência', 'ar', 'ares', 'aspeto', 'exterior', 'exterioridade', 'mostra', 'semblante', 'visos'],
  ['apedrejar', 'lapidar'],
  ['agravo', 'apelação', 'recurso'],
  ['apenas', 'exclusivamente', 'somente', 'só'],
  ['apêndice', 'suplemento'],
  ['apertado', 'estreito'],
  ['cimo', 'cume', 'cumeada', 'cumeeira', 'ápice'],
  ['apócrifo', 'fictício', 'pretenso', 'suposto'],
  ['apologia', 'defesa', 'elogio', 'justificação'],
  ['aposentar', 'jubilar', 'reformar'],
  ['apossar-se', 'apropriar-se', 'conquistar', 'invadir', 'usurpar'],
  ['apóstolo', 'evangelizador', 'missionário'],
  ['apreço', 'consideração', 'conta', 'estima'],
  ['apreender', 'apresar', 'arrestar', 'prender'],
  ['aparecer', 'apresentar-se', 'comparecer'],
  ['aprisco', 'curral', 'mangueira', 'redil'],
  ['aprofundar', 'profundar'],
  [
    'aptidão',
    'capacidade',
    'disposição',
    'gosto',
    'habilidade',
    'idoneidade',
    'inclinação',
    'jeito',
    'propensão',
    'talento',
    'vocação',
  ],
  ['aqui', 'cá'],
  ['ardil', 'armadilha', 'arteirice', 'astúcia', 'cilada', 'emboscada', 'estratagema', 'logro'],
  [
    'custoso',
    'dificultoso',
    'difícil',
    'doloroso',
    'espinhoso',
    'fatigante',
    'intrincado',
    'penoso',
    'trabalhoso',
    'árduo',
    'ímprobo',
  ],
  ['superfície', 'área'],
  ['aridez', 'estéril', 'seco', 'sequidade', 'árido'],
  ['armada', 'esquadra', 'esquadrilha', 'frota'],
  ['armistício', 'suspensão de armas', 'tréguas'],
  ['aroma', 'aromas', 'fragrância', 'perfume'],
  ['arrancar', 'arrebatar', 'extrair', 'sacar', 'tirar'],
  ['arrependimento', 'pesar', 'remorso'],
  ['arroio', 'regato', 'regueiro', 'ribeira', 'ribeiro'],
  ['arte', 'artificial', 'artifício', 'artístico'],
  ['arte', 'mister', 'ofício', 'profissão – “posto'],
  ['arte', 'ciência'],
  ['artesano', 'artesão', 'artista', 'artífice'],
  ['boreal', 'norte', 'setentrional', 'ártico'],
  ['articular', 'dizer', 'proferir', 'pronunciar'],
  ['artificial', 'factício', 'falso', 'ficto', 'fictício', 'fingido', 'simulado'],
  ['artificial', 'artificioso'],
  ['artefacto', 'artifício'],
  ['brasa', 'áscua'],
  ['assassinar', 'massacrar', 'matar', 'trucidar'],
  ['assassinato', 'assassino', 'assassínio', 'homicida', 'homicídio', 'matador', 'matança', 'morte', 'morticínio'],
  ['assaz', 'bastante', 'suficiente'],
  ['assédio', 'bloqueio', 'cerco', 'sítio'],
  ['assíduo', 'frequente'],
  ['assinar', 'firmar', 'subscrever'],
  ['assoante', 'assonância', 'consoante', 'consonância', 'rima', 'rimado'],
  ['assunto', 'matéria', 'objeto'],
  ['astrologia', 'astronomia'],
  ['assento', 'ata', 'auto', 'registro', 'termo'],
  ['ataúde', 'caixão', 'esquife', 'féretro', 'tumba'],
  [
    'ateu',
    'cético',
    'descrente',
    'descrido',
    'gentil',
    'gentio',
    'idólatra',
    'incrédulo',
    'incréu',
    'infiel',
    'irreligioso',
    'pagão',
    'sacrílego',
    'ímpio',
  ],
  ['apercepção', 'aplicação', 'atenção', 'contensão', 'meditação', 'ponderação', 'reflexão'],
  [
    'atentado',
    'crime',
    'culpa',
    'delito',
    'falta',
    'infração',
    'pecado',
    'quebra',
    'quebrantamento',
    'tentativa',
    'transgressão',
    'violação',
  ],
  ['atitude', 'gesto', 'posição', 'postura'],
  [
    'afadigado',
    'afanoso',
    'ansioso',
    'apressurado',
    'ativo',
    'cuidadoso',
    'desvelado',
    'diligente',
    'experto',
    'moirejante',
    'pressuroso',
    'solerte',
    'solícito',
    'zeloso',
  ],
  ['ativo', 'eficaz', 'enérgico', 'forte', 'violento'],
  ['artista', 'ator', 'comediante', 'cômico'],
  ['atribuir', 'imputar'],
  ['atributo', 'predicado', 'propriedade', 'qualidade'],
  ['agora', 'atual', 'atualmente', 'hoje', 'presente', 'presentemente'],
  ['agir', 'atuar', 'influir', 'obrar', 'operar'],
  ['aguentar', 'aturar', 'padecer', 'sofrer', 'suportar', 'tolerar'],
  ['atordoar', 'aturdir', 'conturbar', 'perturbar'],
  ['augusto', 'glorioso', 'grandioso', 'imponente', 'majestoso', 'pontifical', 'soberano', 'solene'],
  ['ampliar-se', 'amplificar-se', 'aumentar', 'avolumar-se', 'avultar', 'crescer', 'engrandecer'],
  ['aragem', 'aura', 'brisa', 'favônio', 'viração', 'zéfiro'],
  ['auspícios', 'patrocínio', 'proteção', 'salvaguarda'],
  ['auspicioso', 'esperançoso', 'prometedor'],
  ['austero', 'duro', 'inabalável', 'inexorável', 'inflexível', 'rigoroso', 'rígido', 'ríspido', 'severo'],
  ['autêntico', 'formal', 'solene'],
  ['autonomia', 'independência', 'soberania'],
  ['autor', 'escritor', 'publicista'],
  ['autoridade', 'força', 'poder', 'potestade'],
  ['apreciar', 'apreçar', 'apreçar', 'avaliar'],
  ['avarento', 'avaro', 'fona', 'sovina', 'ávido'],
  ['avaria', 'estrago', 'lesão', 'perda', 'prejuízo'],
  ['ave', 'pássaro', 'volátil'],
  ['averiguar', 'constatar', 'reconhecer', 'verificar'],
  ['anverso', 'avesso', 'inverso', 'reverso', 'verso'],
  ['avistar', 'bispar', 'descobrir', 'devisar', 'discernir', 'distinguir', 'enxergar', 'lobrigar', 'ver'],
  ['avivar', 'aviventar'],
  ['azado', 'conveniente', 'oportuno', 'próprio'],
  ['agoirento', 'aziago', 'funesto', 'infausto', 'nefasto'],
  ['bailado', 'baile', 'dança', 'fandango', 'folgança', 'folia', 'jongo', 'samba'],
  ['bala', 'projetil'],
  ['balancear', 'balançar', 'duvidar', 'embalançar', 'hesitar', 'vacilar'],
  ['balbuciar', 'gaguejar', 'tartamudear'],
  ['banal', 'comum', 'ordinário', 'trivial', 'vulgar'],
  ['bancarrota', 'falência', 'quebra'],
  ['banda', 'charanga', 'fanfarra', 'filarmônica', 'música', 'orquestra'],
  ['bandeira', 'estandarte', 'insígnia', 'pavilhão', 'vexilo'],
  ['bandido', 'bandoleiro', 'celerado', 'facínora', 'malfeitor', 'salteador'],
  ['banir', 'degredar', 'deportar', 'desterrar', 'exilar', 'expatriar', 'proscrever'],
  ['barbaridade', 'crueldade', 'crueza', 'desumanidade', 'fereza', 'ferocidade'],
  ['barbarismo', 'solecismo'],
  ['bárbaro', 'selvagem'],
  ['barco', 'embarcação', 'fragata', 'nau', 'navio'],
  ['bardo', 'rapsoda', 'trovador', 'vate'],
  ['bastardo', 'espúrio', 'ilegítimo', 'natural'],
  ['batologia', 'redundância', 'tautologia'],
  ['beato', 'carola', 'hipócrita', 'tartufo'],
  ['beiço', 'lábio'],
  ['belicoso', 'bélico', 'guerreiro', 'marcial', 'militar'],
  ['beneficência', 'caridade', 'filantropia'],
  ['benefício', 'favor', 'graça', 'mercê', 'obséquio'],
  ['biblioteca', 'livraria'],
  ['bispado', 'diocese', 'episcopado', 'mitra'],
  ['boiar', 'flutuar', 'nadar', 'sobrenadar'],
  ['bala', 'bola', 'esfera', 'globo', 'pelouro'],
  ['bolha', 'borbulha', 'empola', 'vesícula'],
  ['borbotão', 'cachão', 'golfada', 'gorgolhão', 'jacto', 'jorro', 'torrente'],
  ['borda', 'margem', 'riba', 'ribança', 'ribeira'],
  ['bastão', 'bordão', 'cajado', 'pau', 'varapau'],
  ['aguaceiro', 'borrasca', 'procela', 'refrega', 'tempestade', 'temporal', 'tormenta', 'vendaval'],
  ['arvoredo', 'bosque', 'capoeira', 'capão', 'floresta', 'luco', 'mata', 'restinga', 'selva', 'sertão', 'tapera'],
  ['bossa', 'corcova', 'corcunda', 'giba', 'gibosidade'],
  ['botão', 'broto', 'gema', 'gomo', 'olho', 'rebento', 'renovo'],
  ['botica', 'farmácia'],
  ['bota', 'botim', 'botina', 'calçado', 'sapato'],
  ['breve', 'conciso', 'curto', 'lacônico', 'preciso', 'sucinto'],
  ['brilhante', 'diamante'],
  [
    'brilhar',
    'cintilar',
    'esplender',
    'fulgurar',
    'luzir',
    'rebrilhar',
    'reluzir',
    'resplandecer',
    'resplendecer',
    'resplender',
    'transluzir',
    'tremeluzir',
  ],
  ['brinde', 'dom', 'donativo', 'dádiva', 'presente'],
  ['bruma', 'caligem', 'nevoeiro', 'nuvem', 'névoa'],
  ['bufo', 'bufão', 'burlesco', 'cômico', 'grotesco'],
  ['buscar', 'procurar'],
  ['cabeleira', 'cabelo', 'coma', 'grenha', 'guedelha', 'madeixa', 'marrafa', 'melena'],
  ['cabedelo', 'cabo', 'pontal', 'promontório'],
  ['cachoeira', 'cascata', 'catadupa', 'catarata', 'corredeira', 'rápido', 'salto'],
  ['cadafalso', 'forca', 'guilhotina', 'patíbulo'],
  [
    'caducidade',
    'caduco',
    'caduquice',
    'decrepitude',
    'decrépito',
    'invalidez',
    'inválido',
    'senectude',
    'senilidade',
    'velhice',
    'velho',
  ],
  ['calado', 'mudo', 'silencioso', 'taciturno'],
  ['calcular', 'computar', 'contar', 'cálculo'],
  [
    'atalho',
    'azinhaga',
    'caminho',
    'carreiro',
    'estrada',
    'picada',
    'raia',
    'senda',
    'trilha',
    'vereda',
    'via',
    'vicina',
  ],
  ['cansaço', 'canseira', 'fadiga', 'lassidão'],
  ['canto', 'canção', 'cântico', 'hino'],
  ['arguto', 'capcioso', 'insidioso', 'sofístico'],
  ['capitulação', 'rendição'],
  ['cabido', 'capítulo'],
  ['cara', 'face', 'frente', 'fronte', 'rosto', 'semblante', 'vulto'],
  ['caráter', 'compleição', 'constituição', 'gênio', 'humor', 'natural', 'temperamento', 'índole'],
  ['arcaboiço', 'carcaça', 'esqueleto'],
  ['carecer', 'necessitar', 'precisar'],
  [
    'carestia',
    'careza',
    'carência',
    'escassez',
    'fome',
    'indigência',
    'inópia',
    'miséria',
    'necessidade',
    'penúria',
    'pobreza',
    'sede',
  ],
  ['cargo', 'emprego', 'encargo', 'ministério'],
  ['caridoso', 'caritativo'],
  ['carniceiro', 'carnívoro'],
  ['bilhete', 'carta', 'epístola', 'missiva'],
  ['casa', 'morada', 'palacete', 'palácio', 'vivenda'],
  ['caso', 'circunstância', 'conjuntura', 'situação'],
  [
    'castidade',
    'casto',
    'continente',
    'continência',
    'ilibado',
    'impoluto',
    'incorrupto',
    'intemerato',
    'pureza',
    'puro',
    'virgem',
    'virgindade',
  ],
  ['castigar', 'castigo', 'pena', 'punir', 'punição'],
  ['catálogo', 'lista', 'nomenclatura', 'rol'],
  ['cativeiro', 'cativo', 'escravidão', 'escravo'],
  ['causa', 'motivo', 'móvel', 'pretexto', 'razão'],
  ['causticante', 'cáustico', 'irônico', 'mordaz', 'mordente', 'pungente', 'pungitivo', 'satírico'],
  ['cegamente', 'às cegas'],
  ['celebrar', 'comemorar', 'festejar', 'rememorar', 'solenizar'],
  ['celeste', 'celestial', 'célico', 'divinal', 'divino'],
  ['celibatário', 'solteiro'],
  [
    'campa',
    'carneiro',
    'catacumbas',
    'cenotáfio',
    'cova',
    'hipogeu',
    'jazigo',
    'mausoléu',
    'monumento',
    'sarcófago',
    'sepulcro',
    'sepultura',
    'túmulo',
  ],
  ['admoestação', 'censura', 'crítica', 'sátira'],
  ['cerimônia', 'liturgia', 'rito', 'ritual'],
  ['chama', 'chispa', 'fagulha', 'faísca', 'flama', 'fogo', 'fogueira', 'incêndio', 'labareda', 'lume'],
  ['atrativo', 'chamariz', 'engodo', 'isca', 'negaça', 'reclamo'],
  ['chapada', 'esplanada', 'planalto', 'planura'],
  ['cheia', 'dilúvio', 'enchente', 'inundação'],
  ['chistoso', 'espirituoso', 'faceto', 'gracioso'],
  ['chocalheiro', 'chocarreiro', 'garabulho', 'linguareiro', 'linguarudo', 'pernóstico'],
  ['chocar', 'incubar'],
  ['chocar', 'melindrar', 'ofender'],
  ['choque', 'conflito', 'embate', 'encontro'],
  ['carpir', 'chorar', 'gemer', 'lagrimar', 'lamentar', 'prantear', 'soluçar'],
  ['castelo', 'cidade fortificada', 'cidadela', 'fortaleza', 'forte', 'fortim', 'praça'],
  ['cifra', 'nada', 'zero'],
  ['boêmio', 'cigano', 'vagabundo', 'valdevino'],
  ['cimentar', 'consolidar', 'firmar', 'prender'],
  ['cínico', 'desavergonhado', 'descarado', 'despudorado', 'desvergonhado', 'impudente'],
  ['apertar', 'cercar', 'cingir', 'circular', 'rodear'],
  ['burilar', 'cinzelar', 'entalhar', 'esculpir', 'gravar', 'imprimir', 'lavorar', 'lavorear', 'lavrar'],
  ['circunlocução', 'circunlóquio', 'perífrase'],
  ['cioso', 'ciumento', 'ciúme', 'inveja', 'invejoso', 'zelo', 'zeloso'],
  ['civil', 'cível'],
  ['civil', 'cívico'],
  ['civilização', 'cultura', 'instrução', 'polícia'],
  ['civismo', 'cívico', 'patriotismo', 'patriótico'],
  ['brilho', 'claridade', 'clarão', 'esplendor', 'fulgor', 'lampejo', 'luar', 'lume', 'luz'],
  ['clareza', 'claridade', 'perspicuidade'],
  ['claro', 'diáfano', 'perspícuo', 'translúcido', 'transparente'],
  ['camada', 'categoria', 'classe', 'grupo', 'hierarquia', 'jerarquia'],
  ['classe', 'espécie', 'família', 'gênero', 'ordem'],
  ['arranjar', 'classificar', 'coordenar', 'dispor', 'distribuir', 'ordenar', 'separar'],
  ['cláusula', 'frase', 'oração', 'período', 'proposição', 'sentença', 'trecho'],
  [
    'benignidade',
    'bondade',
    'caridade',
    'clemência',
    'comiseração',
    'compaixão',
    'dó',
    'humanidade',
    'indulgência',
    'inocência',
    'miseração',
    'misericórdia',
    'pena',
    'piedade',
    'tolerância',
  ],
  ['clérigo', 'eclesiástico', 'padre', 'presbítero', 'religioso', 'sacerdote'],
  ['cliente', 'comitente', 'constituinte'],
  ['clientela', 'clínica'],
  ['coagir', 'constranger', 'forçar', 'obrigar'],
  ['casca', 'cortiça', 'crosta', 'crusta', 'côdea'],
  ['coetâneo', 'coevo', 'contemporâneo'],
  ['camarada', 'coirmão', 'colega', 'companheiro', 'confrade', 'consócio'],
  ['colossal', 'desabalado', 'enorme', 'gigantesco', 'monstruoso'],
  ['coluna', 'esteio', 'pedestal', 'pilar', 'pilastra'],
  ['coma', 'letargia', 'modorra', 'sopor', 'torpor'],
  ['autoridade', 'comando', 'direção', 'governo', 'mando', 'ordem'],
  ['começar', 'principiar'],
  ['comédia', 'entremez', 'farsa', 'pantomima'],
  ['comerciante', 'mercador', 'negociante'],
  ['cometer', 'fazer', 'perpetrar', 'praticar'],
  ['cometimento', 'empreendimento', 'empresa'],
  ['comilão', 'faminto', 'glutão', 'guloso', 'voraz'],
  ['assim como', 'como', 'do mesmo modo'],
  ['compacto', 'denso', 'espesso'],
  ['amiserar-se', 'apiedar-se', 'compadecer-se', 'condoer-se', 'enternecer-se'],
  ['associação', 'companhia', 'sindicato', 'sociedade'],
  ['colacionar', 'comparar', 'conferir', 'confrontar', 'cotejar'],
  ['compartilhar', 'compartir', 'participar', 'partilhar'],
  ['compassado', 'lento', 'tardio', 'vagaroso'],
  ['compatriota', 'compatrício', 'patrício'],
  ['compensar', 'indenizar', 'reparar', 'ressarcir'],
  ['compensar', 'contrabalançar', 'igualar'],
  ['competição', 'competência'],
  ['capacidade', 'competência'],
  ['adequado', 'competente', 'próprio', 'respetivo'],
  ['competir', 'concorrer', 'emular', 'rivalizar'],
  ['acabamento', 'complemento', 'completação', 'conclusão', 'implemento', 'suplemento'],
  ['complexo', 'complicado', 'implexo', 'implicado'],
  ['compreender', 'conceber', 'entender'],
  ['comum', 'geral', 'público'],
  ['comumente', 'de ordinário', 'de regra', 'em regra', 'geralmente', 'ordinariamente'],
  ['comuna', 'concelho', 'município'],
  ['conceder', 'outorgar'],
  ['conceito', 'juízo', 'opinião'],
  ['compreensão', 'concepção', 'entendimento', 'intelecto', 'inteligência', 'mente', 'razão'],
  ['açular', 'concitar', 'induzir', 'instigar', 'insuflar', 'provocar'],
  ['coligir', 'concluir', 'deduzir', 'induzir', 'inferir'],
  ['conclusão', 'consequência', 'indução'],
  [
    'concupiscência',
    'lascívia',
    'libidinagem',
    'lubricidade',
    'luxúria',
    'moleza',
    'molícia',
    'sensualidade',
    'voluptuosidade',
    'volúpia',
  ],
  ['conferência', 'entrevista'],
  ['certeza', 'confiança', 'fé'],
  ['confiança', 'segurança', 'seguridade'],
  ['configuração', 'conformação', 'figura'],
  ['apenar', 'apreender', 'arrestar', 'confiscar', 'embargar', 'penhorar', 'sequestrar'],
  ['conforme', 'segundo'],
  ['confortar', 'consolar'],
  ['confraria', 'congregação', 'irmandade', 'ordem'],
  ['confutar', 'impugnar', 'rebater', 'refutar'],
  ['conjugal', 'matrimonial', 'nupcial'],
  ['consorte', 'cônjuge', 'esposo', 'marido', 'mulher', 'senhora'],
  ['conivente', 'conivência', 'cumplicidade'],
  ['consagrar', 'dedicar', 'oferecer', 'ofertar'],
  ['cabala', 'conjuração', 'conluio', 'conspiração', 'enredo', 'intriga', 'mexerico', 'trama'],
  ['construir', 'edificar', 'fabricar', 'fazer'],
  [
    'constante',
    'fiel',
    'firme',
    'forte',
    'inabalável',
    'inalterável',
    'inflexível',
    'leal',
    'obstinado',
    'perseverante',
    'persistente',
    'teimoso',
    'tenaz',
  ],
  ['contestável', 'duvidoso', 'hipotético', 'incerto', 'problemático'],
  ['contribuição', 'derrama', 'direitos', 'finta', 'imposto', 'páreas', 'subsídios', 'taxa', 'tributo'],
  ['contubérnio', 'convivência', 'convívio'],
  ['conveniente', 'decente', 'decoroso', 'discreto', 'honesto'],
  ['conferência', 'conversa', 'conversação'],
  ['convicção', 'persuasão'],
  ['certo', 'convincente', 'evidente', 'incontestável', 'indubitável', 'persuasivo', 'persuasório', 'suasório'],
  ['convir', 'cumprir', 'importar', 'relevar'],
  ['comensal', 'convidado', 'conviva'],
  ['coonestar', 'justificar'],
  ['colaborar', 'cooperar'],
  ['calcar', 'colar', 'copiar', 'decalcar', 'plagiar', 'transcrever', 'trasladar'],
  ['abundante', 'copioso', 'muito', 'numeroso'],
  ['coroa', 'diadema'],
  ['castiço', 'clássico', 'correto', 'correção', 'exato', 'lídimo', 'perfeito', 'puro', 'vernáculo'],
  ['corso', 'corsário', 'flibusteiro', 'pirata', 'pirataria'],
  ['corte', 'fio', 'gume'],
  ['cosmogonia', 'cosmografia', 'cosmologia'],
  ['costume', 'hábito', 'rotina', 'uso'],
  ['covarde', 'fraco', 'poltrão', 'pusilânime'],
  ['crápula', 'deboche', 'libertinagem', 'orgia'],
  ['crasso', 'grosseiro', 'palmar'],
  ['criar', 'gerar', 'produzir'],
  ['crebro', 'frequente', 'reiterado', 'repetido'],
  ['crença', 'fé', 'opinião'],
  ['crer', 'julgar', 'pensar', 'presumir', 'supor'],
  ['antologia', 'coletânea', 'coleção', 'crestomatia', 'florilégio', 'polianteia', 'seleta', 'silva'],
  ['cultivo', 'cultura'],
  ['cumprir', 'guardar', 'observar'],
  ['dama', 'dona', 'matrona', 'mulher', 'senhora'],
  ['danoso', 'nocivo', 'pernicioso', 'prejudicial'],
  ['dar', 'doar', 'dom', 'donativo', 'dote', 'dádiva'],
  ['debilitado', 'débil', 'enfraquecido', 'fraco'],
  ['bosquejo', 'debuxo', 'esboceto', 'esboço'],
  ['decair', 'descair'],
  ['decapitar', 'degolar', 'descabeçar', 'guilhotinar'],
  ['decoro', 'decência', 'dignidade', 'gravidade', 'honor', 'honra', 'pudor', 'recato', 'reserva'],
  ['decepção', 'desengano', 'desilusão'],
  ['codilho', 'decepção', 'engano', 'ilusão', 'logro', 'surpresa'],
  [
    'anunciar',
    'declarar',
    'descobrir',
    'desvendar',
    'divulgar',
    'expor',
    'manifestar',
    'noticiar',
    'patentear',
    'promulgar',
    'publicar',
    'revelar',
  ],
  ['analisar', 'anatomizar', 'decompor', 'destrinçar', 'dissecar', 'escalpelar', 'esmiuçar', 'examinar'],
  ['aviso', 'decreto', 'lei', 'resolução'],
  ['defeito', 'deformidade', 'imperfeição'],
  ['defender', 'justificar'],
  ['defender', 'estorvar', 'impedir', 'inibir', 'interditar', 'interdizer', 'obstar', 'proibir', 'vedar'],
  ['decidir', 'deliberar', 'opinar', 'resolver', 'votar'],
  ['delicadeza', 'delicado', 'fineza', 'fino', 'finura', 'leve', 'subtil', 'subtileza', 'tênue'],
  ['acusado', 'criminoso', 'delinquente', 'réu'],
  ['demo', 'demônio', 'diabo', 'diacho', 'satã'],
  ['deplorável', 'lamentável', 'lastimável'],
  ['depois', 'logo'],
  ['demitir', 'depor', 'destituir', 'dispensar'],
  ['de repente', 'de súbito', 'repentinamente', 'subitamente'],
  ['decorrer', 'derivar', 'proceder', 'provir', 'vir'],
  ['derramar', 'entornar'],
  ['derreter', 'dissolver', 'fundir', 'liquefazer'],
  ['aniquilar', 'bater', 'derrotar', 'desbaratar', 'desfazer', 'destroçar', 'destruir', 'exterminar'],
  ['agressivo', 'desabrido', 'hostil', 'violento'],
  ['desaconselhar', 'desconvencer', 'desenganar', 'desiludir', 'despersuadir', 'dissuadir'],
  ['desafio', 'duelo', 'provocação', 'repto'],
  ['desandar', 'recuar', 'regressar', 'retornar', 'retroceder', 'retrogradar', 'tornar', 'voltar', 'volver'],
  ['desapegar', 'despegar'],
  ['desapercebido', 'despercebido'],
  ['desarranjar', 'desordenar', 'transtornar'],
  ['desarrugar', 'desenrugar'],
  ['desavença', 'dissensão', 'dissentimento'],
  [
    'bonança',
    'calma',
    'descanso',
    'paz',
    'placidez',
    'quietação',
    'quietude',
    'repouso',
    'serenidade',
    'sossego',
    'tranquilidade',
  ],
  ['desconhecido', 'incógnito'],
  ['descorado', 'lívido', 'macilento', 'pálido'],
  [
    'desatencioso',
    'descortês',
    'grosseiro',
    'impolido',
    'impolítico',
    'incivil',
    'indelicado',
    'inurbano',
    'rústico',
    'tosco',
  ],
  ['desculpa', 'escusa', 'perdão', 'recusa'],
  ['desdizer-se', 'retratar-se'],
  ['deserto', 'despovoado', 'ermo', 'solitário'],
  ['deserto', 'ermo', 'soidão', 'soledade', 'solidão'],
  ['desertor', 'trânsfuga'],
  ['deserdar', 'exerdar'],
  ['assinalar', 'designar', 'indicar', 'sinalar'],
  ['desembaraçar', 'desimpedir', 'desobstruir'],
  ['desnecessário', 'escusado', 'supérfluo'],
  ['desapossar', 'despojar', 'esbulhar', 'espoliar', 'extorquir', 'privar'],
  ['desquite', 'divórcio', 'repúdio'],
  ['dessepulto', 'insepulto'],
  ['desvanecer', 'dissipar'],
  ['cessar', 'deter', 'interromper', 'parar', 'sobrestar', 'sustar'],
  ['detritos', 'fezes', 'lia', 'resíduo', 'sedimento'],
  ['dever', 'obrigação'],
  ['devolver', 'restituir'],
  ['demoníaco', 'diabólico', 'infernal', 'satânico'],
  ['dialética', 'lógica'],
  ['dialecto', 'idioma', 'linguagem', 'língua'],
  ['diurno', 'diário', 'quotidiano'],
  ['dicção', 'elocução', 'estilo', 'expressão', 'frase', 'palavra', 'termo', 'vocábulo', 'voz'],
  ['dicionário', 'elucidário', 'glossário', 'léxico', 'vocabulário'],
  ['diferença', 'dissemelhança', 'distinção'],
  ['dificuldade', 'embaraço', 'empecilho', 'estorvo', 'impedimento', 'obstáculo'],
  ['comprido', 'difuso', 'prolixo', 'proluxo'],
  ['digressão', 'distração', 'divagação', 'diversão'],
  ['cortar', 'despedaçar', 'dilacerar', 'espedaçar', 'golpear', 'lacerar', 'rasgar', 'retalhar'],
  [
    'consumir',
    'desbaratar',
    'desperdiçar',
    'dilapidar',
    'dissipar',
    'esbanjar',
    'esperdiçar',
    'estragar',
    'gastar',
    'malbaratar',
    'prodigalizar',
  ],
  ['dimanar', 'efluir', 'emanar', 'fluir', 'manar'],
  ['direito', 'jurisprudência'],
  ['direito', 'justiça'],
  ['conduzir', 'dirigir', 'guiar', 'levar'],
  ['critério', 'discernimento', 'juízo', 'tino'],
  ['diserto', 'elegante', 'eloquente', 'facundo'],
  ['caro', 'custoso', 'dispendioso'],
  [
    'direito',
    'dispensa',
    'escusa',
    'exenção',
    'franquia',
    'imunidade',
    'isenção',
    'liberdade',
    'licença',
    'prerrogativa',
    'privilégio',
    'regalia',
  ],
  ['derramar', 'difundir', 'disseminar', 'distribuir', 'espalhar', 'semear'],
  ['conselho', 'ditame', 'opinião', 'parecer', 'voto'],
  ['dividir', 'repartir'],
  ['divisa', 'emblema', 'empresa', 'símbolo'],
  [
    'brando',
    'doce',
    'docilidade',
    'dócil',
    'flexível',
    'macio',
    'manso',
    'meigo',
    'obediente',
    'obediência',
    'pacífico',
    'suave',
    'submisso',
    'tratável',
  ],
  [
    'assistência',
    'demora',
    'detença',
    'domicílio',
    'estada',
    'estadia',
    'morada',
    'moradia',
    'parada',
    'permanência',
    'residência',
  ],
  ['detentor', 'dono', 'proprietário', 'senhor'],
  ['donzela', 'menina', 'moça', 'rapariga'],
  [
    'culto',
    'douto',
    'erudito',
    'esclarecido',
    'ilustrado',
    'instructo',
    'instruído',
    'perito',
    'sabedor',
    'sapiente',
    'sábio',
    'versado',
  ],
  ['duração', 'eternidade', 'tempo'],
  ['ebulição', 'efervescência', 'fervor', 'fervura'],
  [
    'aguardentado',
    'alcoolizado',
    'avinhado',
    'borracho',
    'bêbado',
    'ebrioso',
    'embebedado',
    'emborrachado',
    'embriagado',
    'encachaçado',
    'inebriado',
    'temulento',
    'ébrio',
  ],
  ['catafalco', 'cenotáfio', 'eça'],
  ['bucólica', 'idílio', 'pastoral', 'poesia pastoril', 'écloga'],
  ['econômico', 'parcimonioso', 'parco', 'poupado'],
  ['editor', 'edição', 'impressor', 'impressão'],
  ['civilização', 'criação', 'educação', 'ilustração', 'instrução'],
  ['efetuar', 'executar', 'fazer', 'realizar'],
  ['cópia', 'efígie', 'fotografia', 'imagem', 'retrato'],
  ['eleger', 'eleição', 'escolha', 'escolher', 'preferir', 'preferência'],
  ['embaixador', 'encarregado de negócios', 'enviado', 'internúncio', 'legado', 'ministro', 'núncio'],
  ['embrião', 'feto', 'gérmen', 'semente', 'sêmen'],
  ['ardil', 'artifício', 'astúcia', 'embuste', 'estratagema', 'manha', 'mentira', 'patranha', 'peta'],
  ['comodato', 'empréstimo', 'mutuação', 'mútuo'],
  ['encarecer', 'exagerar'],
  ['azo', 'conjunção', 'ensejo', 'ocasião', 'oportunidade'],
  ['enterramento', 'enterro', 'exéquias', 'funeral', 'saimento'],
  ['distrair', 'divertir', 'entreter', 'espairecer'],
  ['despachar', 'enviar', 'expedir', 'mandar', 'remeter'],
  ['desenlace', 'desfecho', 'epílogo', 'peroração'],
  ['era', 'período', 'época'],
  ['equidade', 'justiça', 'retidão'],
  ['erário', 'fisco', 'tesouro'],
  [
    'constituir',
    'construir',
    'erguer',
    'erigir',
    'estabelecer',
    'formar',
    'fundar',
    'instituir',
    'levantar',
    'organizar',
  ],
  ['escapar', 'esquivar', 'evadir', 'evitar', 'fugir'],
  [
    'carambina',
    'caramelo',
    'chuva de pedra',
    'escarcha',
    'geada',
    'gelo',
    'granizo',
    'neve',
    'pedrisco',
    'saraiva',
    'sincelos',
  ],
  ['deslizar', 'escorregar', 'resvalar'],
  ['escuro', 'obscuro', 'sombrio', 'tenebroso'],
  ['atender', 'escutar', 'ouvir'],
  ['esfaimado', 'esfomeado', 'faminto', 'famulento', 'femélico'],
  ['cansado', 'esfalfado', 'extenuado', 'fatigado'],
  ['alinho', 'apuro', 'asseio', 'capricho', 'correção', 'cuidado', 'esmero', 'gosto', 'limpeza', 'primor', 'requinte'],
  ['espantoso', 'horrendo', 'horroroso', 'horrível', 'terrificante', 'terrífico', 'terrível'],
  ['especial', 'particular', 'privativo', 'singular'],
  ['confiança', 'esperança', 'fé'],
  ['atalaia', 'espia', 'espião', 'sentinela', 'vigia'],
  ['espiar', 'espionar', 'espreitar'],
  ['espontâneo', 'livre', 'voluntário'],
  ['estado', 'nação', 'povo'],
  ['contínuo', 'eterno', 'imortal', 'perpétuo'],
  ['eumênides', 'fúrias'],
  ['amaldiçoar', 'execrar', 'execração', 'imprecar', 'imprecação', 'maldizer', 'maldição', 'praga', 'praguejar'],
  ['experiência', 'observação'],
  ['fábrica', 'manufatura', 'oficina', 'tenda', 'usina'],
  ['fachada', 'frente', 'frontaria', 'frontispício'],
  ['faculdade', 'poder', 'potência'],
  ['falecimento', 'morte', 'passamento', 'traspasse', 'trânsito'],
  ['fanal', 'farol'],
  ['enfadonho', 'fastidioso', 'importuno', 'tedioso'],
  ['benigno', 'favorável', 'propício', 'próspero'],
  ['favorito', 'mimo', 'mimoso', 'predileto', 'preferido', 'privado', 'valido'],
  ['abundante', 'farto', 'fecundidade', 'fecundo', 'fertilidade', 'fértil', 'ubertoso', 'úbere'],
  ['congratulações', 'cumprimentos', 'emboras', 'felicitações', 'parabéns', 'saudações'],
  ['afortunado', 'ditoso', 'feliz', 'venturoso'],
  ['ferramenta', 'instrumento', 'utensílios'],
  ['defunto', 'finado', 'morto'],
  ['fluido', 'líquido'],
  ['franco', 'leal', 'sincero'],
  ['dolo', 'doloso', 'fraude', 'fraudulento'],
  ['frívolo', 'fútil'],
  ['fuga', 'fugida'],
  ['básico', 'capital', 'fundamental', 'principal'],
  ['funeral', 'funerário', 'funéreo', 'fúnebre'],
  ['cólera', 'enfurecido', 'furente', 'furial', 'furibundo', 'furioso', 'furor', 'fúria', 'ira', 'raiva'],
  [
    'estelionato',
    'furtar',
    'furto',
    'ladroeira',
    'ladroíce',
    'latrocínio',
    'peculato',
    'plágio',
    'rapina',
    'rapinar',
    'raptar',
    'rapto',
    'roubar',
    'roubo',
  ],
  ['futuro', 'porvindoiro', 'póstero', 'vindoiro'],
  ['galardão', 'gratificação', 'prêmio', 'recompensa', 'comissão'],
  ['charlar', 'cochichar', 'galrar', 'garlar', 'ou'],
  ['ganho', 'ganância', 'interesse', 'lucro'],
  ['abstração', 'generalização'],
  ['generosidade', 'generoso', 'liberal', 'liberalidade', 'munificente', 'munificência'],
  ['geral', 'universal'],
  [
    'celebridade',
    'conceito',
    'crédito',
    'distinção',
    'fama',
    'glória',
    'honra',
    'lustre',
    'nomeada',
    'renome',
    'reputação',
  ],
  ['gosto', 'gozo', 'paladar', 'ranço', 'ressaibo', 'sabor'],
  ['gradação', 'graduação'],
  ['dimensões', 'grandeza', 'grandura', 'magnitude', 'proporções', 'tamanho', 'volume'],
  ['grandíssimo', 'muito grande'],
  ['casa de campo', 'chácara', 'granja', 'quinta'],
  ['gratidão', 'reconhecimento'],
  ['guante', 'luva', 'manopla'],
  ['escolta', 'guarda', 'patrulha', 'piquete', 'ronda'],
  ['harmonia', 'harmonioso', 'harmônico'],
  ['deixa', 'herança', 'hereditariedade', 'legado', 'sucessão'],
  ['herói', 'representativo', 'super-homem'],
  ['anais', 'epopeia', 'fastos', 'história', 'legenda', 'lenda', 'narrativa', 'narração', 'relação'],
  ['historiador', 'historiógrafo'],
  ['humildade', 'humilhação'],
  ['ideal', 'imaginário'],
  ['desonra', 'ignomínia', 'infâmia', 'opróbrio'],
  ['acepipe', 'guloseima', 'iguaria', 'manjar', 'pitéu'],
  ['imaginativa', 'imaginação', 'inventiva'],
  ['imolar', 'imolação', 'sacrificar', 'sacrifício'],
  ['impalpável', 'intangível', 'intáctil'],
  ['imparcial', 'indiferente', 'neutral', 'neutro'],
  ['improrrogável', 'inadiável', 'intransferível'],
  ['inaptidão', 'incapacidade', 'insuficiência'],
  ['ileso', 'incólume'],
  ['inconstante', 'volúvel'],
  ['incerteza', 'incerto', 'indeciso', 'indecisão', 'irresoluto', 'irresolução', 'perplexo'],
  ['fixo', 'inalterável', 'inapagável', 'indelével'],
  ['apatia', 'impassibilidade', 'indiferença', 'indolência', 'inexcitabilidade', 'insensibilidade'],
  ['indivíduo', 'pessoa'],
  ['indizível', 'inefável', 'inexprimível'],
  ['infante', 'infantilidades', 'infância', 'meninice', 'meninices', 'puerilidades', 'puerícia'],
  ['ascendente', 'ascendência', 'ação', 'influxo', 'influência', 'prestígio', 'superioridade'],
  ['informação', 'inquérito', 'perquisição'],
  ['encaixar', 'inserir', 'intercalar', 'interpor'],
  ['insosso', 'insulso', 'insípido'],
  ['desacostumado', 'desusado', 'insólito'],
  ['instante', 'momento'],
  ['insurgente', 'insurgido', 'insurrecionado', 'insurrecto', 'rebelado', 'rebelde', 'sublevado'],
  ['interior', 'interno', 'intrínseco', 'íntimo'],
  ['inválido', 'nulo', 'írrito'],
  ['jamais', 'nunca'],
  ['afirmação', 'jura', 'juramento', 'promessa', 'protesto'],
  ['certame', 'justa', 'torneio'],
  ['largueza', 'largura'],
  ['legal', 'legítimo', 'lícito', 'permitido'],
  ['brunir', 'limar', 'polir'],
  ['filologia', 'filólogo', 'gramática', 'gramático', 'linguista', 'linguística'],
  ['distante', 'longínquo', 'remoto'],
  ['forjar', 'maquinar', 'tecer', 'tramar', 'urdir'],
  ['fonte', 'manadeiro', 'manancial', 'nascente', 'nascença', 'origem'],
  ['mar', 'oceano'],
  ['mas', 'porém'],
  ['cadeia', 'calabouço', 'enxovia', 'masmorra'],
  ['maternal', 'materno', 'paternal', 'paterno'],
  ['matinal', 'matutino'],
  ['medicamento', 'remédio'],
  ['lembrança', 'memória', 'recordação', 'reminiscência', 'retentiva'],
  ['mendicidade', 'mendicância', 'mendigo'],
  ['mercadoria', 'mercancia'],
  ['ceifa', 'colheita', 'messe', 'seara'],
  ['maravilha', 'milagre', 'prodígio'],
  ['espiritual', 'espiritualidade', 'espiritualismo', 'misticidade', 'misticismo', 'místico'],
  ['moda', 'uso', 'voga'],
  ['idiotismo', 'modismo'],
  ['monacal', 'monástico'],
  ['monólogo', 'solilóquio'],
  ['cerro', 'cerrote', 'colina', 'cordilheira', 'montanha', 'monte', 'outeiro', 'serra', 'serrania'],
  ['montanheiro', 'montanhesco', 'montanhoso', 'montanhês', 'montano', 'montuoso'],
  ['mundo', 'orbe', 'universo'],
  ['mútuo', 'recíproco'],
  ['dríade', 'napeia', 'ninfa', 'náiade', 'tágide'],
  ['naval', 'náutico'],
  ['conveniente', 'forçoso', 'indispensável', 'necessário', 'preciso', 'urgente', 'útil'],
  ['nós outros', 'nós'],
  ['manifesto', 'notório', 'público'],
  ['novo', 'recente'],
  ['oblata', 'oblação', 'oferenda', 'oferta'],
  ['côncavo', 'oco', 'vazio', 'vácuo', 'vão'],
  ['cancelar', 'cortar', 'elidir', 'eliminar', 'omitir', 'suprimir'],
  ['escarcéu', 'marouço', 'onda', 'vaga', 'vagalhão'],
  ['onzena', 'usura'],
  ['escolha', 'escolher', 'optar', 'opção', 'preferir', 'preferência'],
  ['outrem', 'outro'],
  [
    'estipêndio',
    'honorários',
    'mensalidade',
    'ordenado',
    'paga',
    'pagamento',
    'remuneração',
    'retribuição',
    'salário',
    'soldada',
    'soldo',
    'vencimentos',
  ],
  ['folha', 'lauda', 'página'],
  ['palpável', 'perceptível', 'sensível', 'visível'],
  ['paralogismo', 'sofisma'],
  ['casal', 'junta', 'par', 'parelha'],
  ['pena', 'saudade'],
  ['percepção', 'sensação', 'sentimento'],
  ['perpendicular', 'vertical'],
  ['poeta', 'vate'],
  ['poesia', 'poética'],
  ['bispo', 'pontífice', 'prelado', 'sacerdote'],
  ['pois que', 'pois', 'porque', 'que', 'qual'],
  ['possuir', 'ter'],
  ['posterior', 'seguinte', 'subsecutivo', 'subsequente', 'ulterior'],
  ['axioma', 'postulado'],
  ['perversidade', 'perversão', 'pravidade'],
  [
    'exórdio',
    'introdução',
    'introito',
    'prefação',
    'prefácio',
    'preliminar',
    'prelúdio',
    'preâmbulo',
    'prolegômenos',
    'proêmio',
    'prólogo',
  ],
  ['expressamente', 'formalmente', 'justamente', 'positivamente', 'precisamente'],
  ['antecipado', 'precoce', 'prematuro', 'temporão'],
  ['primeiro', 'primevo', 'primitivo', 'primário'],
  ['profanação', 'sacrilégio'],
  [
    'ascendência',
    'casa',
    'casta',
    'estirpe',
    'família',
    'genealogia',
    'geração',
    'linhagem',
    'progenitura',
    'progênie',
    'prosápia',
    'raça',
    'sangue',
  ],
  ['mesmo', 'próprio'],
  ['cabriola', 'pinote', 'pirueta', 'pulo', 'salto'],
  ['número', 'quantia', 'quantidade', 'soma'],
  ['fantasia', 'ilusão', 'quimera', 'utopia', 'visão'],
  [
    'chispante',
    'cintilante',
    'coruscante',
    'faiscante',
    'flamante',
    'irradiador',
    'irradiante',
    'radiante',
    'radioso',
    'relampejante',
    'reluzente',
  ],
  ['pegada', 'pisada', 'rasto', 'trilha', 'vestígio'],
  ['real', 'realengo', 'reguengo', 'reiuno', 'régio'],
  [
    'destaque',
    'evidência',
    'preeminente',
    'preeminência',
    'proeminente',
    'proeminência',
    'realce',
    'relevo',
    'ressalto',
    'saliência',
  ],
  ['realidade', 'verdade'],
  ['quitação', 'recibo'],
  ['reaver', 'recobrar', 'recuperar', 'retomar'],
  ['gerente', 'gerir', 'regedor', 'regente', 'reger'],
  ['desforra', 'desforço', 'despique', 'represália', 'retaliação', 'vindicta', 'vingança'],
  ['abdicação', 'paciência', 'passividade', 'renunciamento', 'resignação'],
  ['repercutir', 'ressoar', 'retinir', 'retumbar'],
  ['redarguir', 'replicar', 'retorquir', 'retrucar'],
  ['inspiração', 'revelação'],
  ['diário', 'itinerário', 'portulânio', 'roteiro'],
  ['ciência', 'sabedoria'],
  ['sacro', 'sagrado', 'santo'],
  ['higiênico', 'sadio', 'salubre', 'salutar', 'são'],
  ['sangrento', 'sanguento', 'sanguinolento'],
  ['laical', 'leigo', 'secular'],
  ['carruagem', 'coche', 'sege', 'trem', 'veículo'],
  ['secretar', 'secreção', 'segregar', 'segregação'],
  ['ato contínuo', 'de seguida', 'em seguida', 'imediatamente', 'logo após', 'seguidamente'],
  ['servir de', 'servir para'],
  ['reserva', 'segredo', 'sigilo'],
  ['apito', 'assobio', 'sibilo', 'silvo'],
  ['simpleza', 'simplicidade'],
  ['sistema', 'teoria'],
  ['social', 'sociável'],
  ['soporativo', 'soporoso', 'soporífero', 'soporífico'],
  ['cidadão', 'súbdito', 'vassalo'],
  ['meio-dia', 'sul'],
  ['soberano', 'sumo', 'supremo'],
  ['caldo', 'suco', 'sumo'],
  ['substituto', 'suplente'],
  ['arroubo', 'rapto', 'surto', 'transporte', 'voo'],
  ['cisma', 'desconfiança', 'receio', 'suspeita'],
  ['implícito', 'subentendido', 'tácito'],
  ['baiuca', 'bodega', 'espelunca', 'locanda', 'quiosque', 'taberna', 'tasca', 'taverna', 'venda'],
  ['gago', 'tartamelo', 'tartamudo', 'tatibitate', 'tátaro'],
  ['desconfiar', 'recear', 'suspeitar', 'temer'],
  ['basílica', 'capela', 'ermida', 'igreja', 'igrejinha', 'igrejola', 'igrejário', 'igrejório', 'templo'],
  ['campo', 'solo', 'terra', 'terreno'],
  ['cútis', 'derme', 'epiderme', 'pele', 'tez'],
  ['morno', 'tépido', 'tíbio'],
  ['carimbo', 'marca', 'selo', 'sinete', 'timbre'],
  ['beca', 'garnacha', 'paludamento', 'toga', 'trábea'],
  ['tomo', 'volume'],
  ['desonesto', 'impudico', 'obsceno', 'torpe'],
  ['tradução', 'versão'],
  ['gole', 'hausto', 'sorvo', 'trago'],
  ['trajo', 'vestido', 'vestidura', 'vestimenta'],
  ['tristeza', 'tristura'],
  ['triunfal', 'triunfante'],
  ['mutilar', 'truncar'],
  ['casula', 'dalmática', 'tunicela', 'túnica'],
  ['turno', 'vez'],
  ['chaga', 'ferida', 'úlcera'],
  ['singular', 'só', 'um', 'único'],
  ['junção', 'união'],
  ['pressa', 'urgência'],
  ['conveniente', 'proveitoso', 'vantajoso', 'útil'],
  ['baldado', 'improfícuo', 'inútil', 'vão'],
  ['veracidade', 'veraz', 'verdade', 'verdadeiro', 'veridicidade', 'verídico'],
  ['avenida', 'vial'],
  ['barrote', 'trave', 'viga'],
  ['homem', 'varonil', 'varão', 'viril'],
  ['vital', 'vivaz', 'viável'],
  ['vencedor', 'vitorioso'],
  ['veleidade', 'volição', 'vontade'],
  ['bombo', 'zabumba'],
  ['alganame', 'pastor', 'pegureiro', 'zagal'],
  ['estrábico', 'peto', 'vesgo', 'zanaga', 'zarolho'],
  ['cortesia', 'mesura', 'rapapé', 'salamaleque', 'zumbaia'],
  ['zum-zum', 'zumbido', 'zunido'],
  ['tu', 'vc', 'você'],
  ['é', 'e'],
  ['Saudações', 'viva', 'fala', 'e ai', 'olá', 'iai', 'ea', 'eai', 'oi', 'opa'],
  [
    'Amigo',
    'Companheiro',
    'Colega',
    'Aliado',
    'Parceiro',
    'Irmão',
    'Cúmplice',
    'Amistoso',
    'Afim',
    'Amiguinho',
    'Amiguinha',
    'Conhecido',
    'Contato',
    'Protetor',
    'Solidário',
    'Simpático',
    'Afinado',
    'Familiar',
    'Fraterno',
    'Unido',
    'Confiável',
    'Leal',
    'Generoso',
    'Benevolente',
    'Empático',
    'Compreensivo',
    'Apoiador',
    'Participante',
    'Entusiasta',
    'Amável.',
    'Bondoso',
    'Carinhoso',
    'Colaborador',
    'Cooperativo',
    'Apoiador',
    'Diplomático',
    'Tolerante',
    'Incondicional',
    'Benfeitor',
    'Acolhedor',
    'Cordial',
    'Preocupado',
    'Sincero',
    'Apaixonado',
    'Grato',
    'amiga',
    'amigo',
    'Generoso',
    'Empenhado',
    'Solidário',
    'Leal',
    'Amigável',
    'Protetor.',
  ],
];
