/* eslint-disable max-lines */
export const classes = {
  '0': [
    'aba',
    'base',
    'declive',
    'encosta',
    'falda',
    'flanco',
    'ilharga',
    'ladeira',
    'lado',
    'orla',
    'sopé',
    'vertente',
  ],
  '1': [
    'abas',
    'adjacências',
    'bairros',
    'cercanias',
    'circunvizinhanças',
    'confins',
    'contiguidades',
    'contornos',
    'imediações',
    'proximidades',
  ],
  '2': ['abafar', 'conter', 'reprimir', 'sofrear', 'sufocar'],
  '3': ['abafar', 'abrigar', 'agasalhar', 'cobrir', 'resguardar', 'tapar'],
  '4': ['abafar', 'acoitar', 'atabafar', 'encobrir', 'esconder', 'ocultar', 'receptar', 'reter', 'sonegar'],
  '5': ['abafeira', 'charco', 'lamaçal', 'pântano'],
  '6': ['abaixar', 'abater', 'arriar', 'baixar', 'descer'],
  '7': ['abaixar', 'abater', 'aviltar', 'degradar', 'rebaixar'],
  '8': ['abalançar-se', 'afoitar-se', 'atrever-se'],
  '9': ['abalar', 'azular', 'esgueirar-', 'fugir', 'partir'],
  '10': ['abalar', 'demover', 'dissuadir'],
  '11': ['abalizado', 'assinalado', 'distinto', 'notável'],
  '12': ['abalo', 'agitação', 'comoção', 'convulsão', 'estremecimento', 'terremoto', 'tremor de terra', 'trepidação'],
  '13': ['abalroar', 'aferrar', 'atracar', 'investir'],
  '14': ['abandonar', 'desprezar', 'desproteger'],
  '15': ['abandono', 'desafetação', 'naturalidade'],
  '16': [
    'abaratar',
    'baratear',
    'depreciar',
    'desapreciar',
    'desencarecer',
    'desestimar',
    'embaratecer',
    'malbaratar',
    'menoscabar',
    'menosprezar',
  ],
  '17': ['abantesma', 'espetro', 'fantasma', 'larva'],
  '18': ['abarcar', 'açambarcar', 'monopolizar'],
  '19': ['abarcar', 'abranger', 'compreender'],
  '20': [
    'abarroado',
    'cabeçudo',
    'caprichoso',
    'contumaz',
    'encaprichado',
    'insistente',
    'obstinado',
    'opiniático',
    'pertinaz',
    'teimoso',
    'tenaz',
  ],
  '21': [
    'abastado',
    'apatacado',
    'argentário',
    'banqueiro',
    'capitalista',
    'endinheirado',
    'milionário',
    'opulento',
    'remediado',
    'ricaço',
    'rico',
  ],
  '22': ['abastardar', 'degenerar', 'desfigurar'],
  '23': [
    'abastar',
    'abastecer',
    'aprovisionar',
    'fornecer',
    'fornir',
    'ministrar',
    'municiar',
    'municionar',
    'munir',
    'prover',
    'subministrar',
  ],
  '24': ['abater', 'aluir', 'cair', 'desabar', 'desmoronar'],
  '25': ['abater', 'deitar abaixo', 'demolir', 'derribar'],
  '26': ['abater', 'deminuir', 'descontar', 'minuir'],
  '27': ['abatimento', 'depressão', 'languidez'],
  '28': [
    'abandonar',
    'abdicar',
    'ceder',
    'demitir-se',
    'desistir',
    'desobrigar-se',
    'exonerar-se',
    'largar',
    'recusar',
    'rejeitar',
    'renunciar',
    'resignar',
  ],
  '29': ['abdômen', 'barriga', 'entranha', 'ventre'],
  '30': ['abençoar', 'bendizer', 'benzer', 'louvar'],
  '31': ['abertura', 'fresta', 'greta', 'racha', 'resquício'],
  '32': ['abelhudo', 'entremetido', 'introduzido', 'intrometido', 'intruso', 'metediço', 'oferecido'],
  '33': ['aberto', 'amplo', 'espaçoso', 'largo', 'vasto'],
  '34': ['aberração', 'absurdo', 'contrassenso', 'despropósito', 'desrazão', 'destampatório'],
  '35': ['abestalhado', 'abobado', 'aparvalhado'],
  '36': ['abeirar-se', 'apropinquar-', 'aproximar-se'],
  '37': ['abespinhar-se', 'irritar-se', 'zangar-se'],
  '38': ['abicar', 'abordar', 'ancorar', 'aportar', 'arribar', 'atracar', 'chegar', 'fundear', 'surgir', 'varar'],
  '39': [
    'abismo5',
    'báratro',
    'despenhadeiro',
    'pego',
    'precipício',
    'rodomoinho',
    'sorvedouro',
    'tragadoiro',
    'voragem',
  ],
  '40': ['abjeto', 'desprezível', 'detestável', 'ignóbil'],
  '41': ['abjurar', 'abrenunciar', 'apostatar', 'converter-se', 'desprofessar', 'renegar', 'renunciar', 'trair'],
  '42': ['ablação', 'amputação'],
  '43': ['abnegação', 'altruísmo', 'desambição', 'desamor', 'desapego', 'desinteresse', 'desprendimento'],
  '44': ['abluir', 'apurar', 'lavar', 'limpar', 'purificar'],
  '45': ['ab-rogar', 'abolir', 'derrogar', 'extinguir'],
  '46': ['abonação', 'abono', 'arras', 'caução', 'fiança', 'garantia', 'hipoteca', 'penhor', 'segurança', 'sinal'],
  '47': ['aborígene', 'autóctone', 'indígena', 'nativo', 'natural', 'originário', 'íncola'],
  '48': ['abortar', 'frustrar-se', 'gorar', 'malograr-se'],
  '49': ['abra', 'angra', 'enseada', 'golfo', 'recôncavo'],
  '50': ['abonançar', 'abrandar', 'adoçar', 'apaziguar', 'enternecer', 'moderar', 'serenar', 'suavizar'],
  '51': [
    'abrasador',
    'abrasante',
    'ardente',
    'caloroso',
    'candente',
    'carbonizante',
    'comburente',
    'cálido',
    'cáustico',
    'queimante',
    'queimoso',
    'quente',
  ],
  '52': ['abrasar-se6'],
  '53': ['abreviar', 'encurtar', 'reduzir', 'restringir'],
  '54': ['abrigo', 'amparo', 'asilo', 'coito', 'esconderijo', 'guarida', 'homizio', 'refúgio', 'valhacoito'],
  '55': ['abrir', 'descerrar', 'entreabrir', 'escancarar', 'soabrir'],
  '56': ['abrir', 'desligar', 'desunir', 'separar', 'soltar'],
  '57': ['abrolhos', 'alfaques', 'baixios', 'baixos', 'cachopos', 'escolhos', 'farelhões', 'recifes'],
  '58': ['abrupto', 'alcantilado', 'aprumado', 'empinado', 'escarpado', 'ladeirento', 'íngreme'],
  '59': ['absconso', 'abscôndito', 'clandestino', 'escondido', 'oculto', 'recôndito', 'retruso', 'secreto'],
  '60': ['absolutismo', 'autocracia', 'despotismo'],
  '61': ['absoluto', 'arrogante', 'categórico', 'decisivo', 'definitivo', 'imperativo', 'imperioso'],
  '62': ['absolver', 'anistiar', 'perdoar', 'remitir'],
  '63': [
    'desafinado',
    'desarmônico',
    'desentoado',
    'destemperado',
    'destoante',
    'discordante',
    'discrepante',
    'dissonante',
    'malsoante',
    'ábsono',
  ],
  '64': [
    'absorver',
    'aspirar',
    'beber',
    'chuchar',
    'chupar',
    'comer',
    'consumar',
    'consumir',
    'deglutir',
    'devorar',
    'engolir',
    'sorver',
    'sugar',
    'tragar',
  ],
  '65': ['absorto', 'admirado', 'assombrado', 'enlevado', 'extasiado', 'maravilhado', 'pensativo'],
  '66': ['abster-se', 'abstinência', 'privar-se', 'privação'],
  '67': ['absterso', 'alvo', 'brilhante', 'polido', 'terso'],
  '68': ['abstinente', 'abstêmio', 'frugal', 'sóbrio'],
  '69': ['abstrato', 'abstruso'],
  '70': ['abundância', 'fartura', 'opulência', 'riqueza'],
  '71': [
    'abusão',
    'crendice',
    'fanatismo',
    'patranha',
    'peta',
    'preconceito',
    'prejuízo',
    'preocupação',
    'prevenção',
    'superstição',
  ],
  '72': ['acabar', 'cessar', 'concluir', 'descontinuar'],
  '73': ['acabar', 'falecer', 'fenecer', 'morrer', 'perecer'],
  '74': [
    'abatido',
    'acabado',
    'alquebrado',
    'avelhentado',
    'consumido',
    'desfigurado',
    'envelhecido',
    'gasto',
    'idoso',
    'macerado',
    'quebrado',
    'velho',
  ],
  '75': ['acabado', 'completo', 'magistral', 'perfeito'],
  '76': [
    'aborrecer',
    'acabrunhar',
    'afligir',
    'amofinar',
    'apoquentar',
    'contristar',
    'desgostar',
    'entristecer',
    'humilhar',
    'importunar',
    'magoar',
    'molestar',
    'mortificar',
    'oprimir',
    'vexar',
  ],
  '77': ['academia', 'colégio', 'escola', 'ginásio', 'instituto', 'liceu', 'universidade'],
  '78': ['acalentar', 'agradar', 'amimar', 'consolar'],
  '79': ['acampamento', 'arraial', 'bivaque'],
  '80': [
    'acanhado',
    'acanhamento',
    'apoucado',
    'modesto',
    'modéstia',
    'pudibundo',
    'pudico',
    'timidez',
    'tímido',
    'vergonha',
    'vergonhoso',
  ],
  '81': ['ato', 'ação', 'fato'],
  '82': ['ação', 'batalha', 'combate', 'peleja', 'pugna'],
  '83': ['ação', 'demanda', 'litígio', 'pleito', 'processo'],
  '84': ['acaso', 'fado', 'fadário', 'fortuna', 'sina', 'sorte'],
  '85': ['acaso', 'por acaso', 'porventura'],
  '86': ['acatamento', 'acatar', 'respeitar', 'respeito'],
  '87': ['acautelado', 'avisado', 'cauteloso', 'cauto', 'precatado', 'precavido', 'prevenido'],
  '88': ['acepção', 'sentido', 'significação'],
  '89': ['aceder', 'aderir', 'anuir', 'aquiescer', 'concordar', 'condescender', 'conformar-', 'consentir'],
  '90': ['aceitar', 'receber', 'tomar', 'recebi', 'resgatar'],
  '91': ['acelerar', 'aligeirar', 'apressar', 'apressurar', 'ativar', 'precipitar'],
  '92': ['acento', 'diapasão', 'som', 'sonido', 'soído', 'timbre', 'toada', 'tom'],
  '93': ['acento', 'pronúncia'],
  '94': ['acerbo', 'acre', 'acérrimo', 'azedo', 'ácido'],
  '95': ['acerca de'],
  '96': ['acertar', 'adivinhar', 'atinar'],
  '97': ['acervo', 'monte', 'montão', 'pilha', 'ruma'],
  '98': ['acessório', 'contingente', 'secundário'],
  '99': ['achado', 'descoberta', 'invento', 'invenção'],
  '100': ['achar', 'deparar', 'descobrir', 'encontrar', 'inventar'],
  '101': ['achaque', 'doença', 'enfermidade', 'incômodo', 'incômodos', 'indisposição', 'moléstia'],
  '102': [
    'acidental',
    'aleatório',
    'casual',
    'contingente',
    'eventual',
    'fortuito',
    'imprevisto',
    'incerto',
    'inesperado',
    'inopinado',
    'ocasional',
  ],
  '103': ['acidente', 'catástrofe', 'desastre', 'desgraça'],
  '104': ['aclamar', 'aplaudir', 'proclamar', 'vitoriar'],
  '105': ['aclarar', 'elucidar', 'esclarecer', 'ilustrar'],
  '106': ['acobardar', 'amedrontar', 'intimidar'],
  '107': ['ações', 'fatos', 'façanhas', 'feitos', 'proezas'],
  '108': ['acoitar-se', 'acoitar', 'asilar-se', 'asilar', 'esconder-se', 'esconder', 'ocultar-se', 'ocultar'],
  '109': ['açoitar', 'chicotar', 'verdascar', 'vergastar'],
  '110': ['acomodar', 'adaptar', 'adequar', 'ajustar'],
  '111': ['acompanhar', 'comboiar', 'escoltar', 'seguir'],
  '112': ['aconselhar', 'guiar', 'insinuar', 'sugerir'],
  '113': ['acontecer', 'dar-se', 'ocorrer', 'suceder'],
  '114': ['acordar', 'ajustar', 'assentar', 'combinar', 'concertar', 'concordar', 'convencionar', 'convir'],
  '115': ['acordar', 'despertar'],
  '116': ['acoroçoar', 'alentar', 'animar', 'induzir'],
  '117': ['acorrentar', 'enca dear', 'encorrentar'],
  '118': ['acorrer', 'acudir', 'afluir'],
  '119': ['acossar', 'perseguir'],
  '120': ['acostumar-se', 'dar-se', 'habituar-se'],
  '121': ['acrescentar', 'acrescer', 'aumentar'],
  '122': ['acrescentar', 'adicionar', 'adir', 'aditar', 'agregar', 'ajuntar', 'juntar'],
  '123': ['acreditar', 'crer'],
  '124': ['acro', 'frágil', 'quebradiço'],
  '125': ['acudir', 'amparar', 'auxiliar', 'socorrer'],
  '126': ['acusar', 'delatar', 'denunciar', 'malsinar'],
  '127': ['acusar', 'arguir', 'criminar', 'culpar', 'incriminar', 'inculpar'],
  '128': [
    'adágio',
    'aforismo',
    'anexim',
    'axioma',
    'brocardo',
    'ditado',
    'dito',
    'máxima',
    'paremia',
    'preceito',
    'princípio',
    'provérbio',
    'rifão',
    'sentença',
  ],
  '129': ['adarga', 'broquel', 'escudo', 'pavês', 'rodela'],
  '130': ['adição', 'soma', 'total'],
  '131': ['adiantar', 'antecipar'],
  '132': ['adiantar-se', 'progredir', 'prosperar'],
  '133': ['adepto', 'iniciado', 'sectarista', 'sectário'],
  '134': ['adereçar', 'adornar', 'ataviar', 'embelecer', 'embelezar', 'enfeitar', 'ornamentar', 'ornar'],
  '135': ['adestrar', 'ensinar', 'exercitar', 'instruir'],
  '136': ['adiar', 'aprazar', 'demorar', 'diferir', 'dilatar', 'protelar', 'remanchar', 'retardar', 'transferir'],
  '137': ['adivinhar', 'agoirar', 'profetizar', 'vaticinar'],
  '138': ['adivinho', 'astrólogo', 'bruxo', 'feiticeiro', 'mandingueiro', 'mágico', 'quiromante'],
  '139': ['adjacente', 'contíguo', 'próximo', 'vizinho'],
  '140': ['adjetivo', 'epíteto'],
  '141': ['adido', 'adjunto'],
  '142': ['adjurar', 'conjurar', 'esconjurar', 'exorcizar'],
  '143': ['admiração', 'assombro', 'espanto', 'pasmo'],
  '144': ['admirar', 'apreciar', 'considerar', 'contemplar', 'encarar', 'examinar', 'fitar', 'olhar', 'ver'],
  '145': ['admirável15'],
  '146': ['admitir', 'receber'],
  '147': ['admitir', 'consentir', 'permitir', 'tolerar'],
  '148': ['aconselhar', 'admoestar', 'advertir', 'arguir', 'avisar', 'censurar', 'repreender', 'verberar'],
  '149': ['adoecer', 'enfermar'],
  '150': ['adolescência', 'juventude', 'mocidade'],
  '151': [
    'acatamento',
    'acatar',
    'adorar',
    'adoração',
    'homenagem',
    'honra',
    'honrar',
    'respeito',
    'reverenciar',
    'reverência',
    'venerar',
    'veneração',
  ],
  '152': ['aduana', 'aduaneiro', 'alfandegário', 'alfândega'],
  '153': ['adubar', 'adubo', 'condimentar', 'temperar'],
  '154': ['adular', 'bajular', 'lisonjear', 'louvaminhar'],
  '155': ['adulterar', 'contrafazer', 'falsificar', 'imitar'],
  '156': ['adunar', 'aunar', 'coadunar', 'reunir', 'unir'],
  '157': ['adunco', 'arcado', 'arqueado', 'curvo', 'recurvado'],
  '158': ['aduzir', 'alegar'],
  '159': ['adventício', 'alienígena', 'estrangeiro', 'forasteiro', 'ádvena'],
  '160': ['adversário', 'antagonista', 'rival', 'êmulo'],
  '161': ['adverso', 'contrário', 'desfavorável', 'oposto'],
  '162': ['adversa', 'adversidade', 'desdita', 'desgraça', 'fortuna', 'infelicidade', 'sorte adversa'],
  '163': ['advocacia', 'advocatura'],
  '164': ['advogado', 'causídico', 'defensor', 'jurisconsulto', 'jurista', 'legista', 'letrado', 'rábula'],
  '165': ['advogado', 'defensor', 'intercessor', 'padroeiro', 'patrocinador', 'patrono', 'protetor'],
  '166': ['afabilidade', 'agrado', 'amabilidade', 'civilidade', 'cortesia', 'polidez', 'urbanidade'],
  '167': ['afasia', 'afonia', 'afásico', 'afônico', 'mudez'],
  '168': [
    'afadigamento',
    'aforçuramento',
    'afã',
    'azáfama',
    'fadiga',
    'faina',
    'labor',
    'laboração',
    'labuta',
    'labutação',
    'lavor',
    'lida',
    'luta',
    'trabalho',
  ],
  '169': ['afastar', 'apartar', 'arredar', 'descaminhar', 'desencaminhar', 'deslocar', 'desviar', 'retirar', 'separar'],
  '170': ['aferro', 'apego'],
  '171': ['aferrolhar', 'fechar', 'ferrolho', 'trancar'],
  '172': ['afeição', 'afeto', 'amor', 'inclinação', 'paixão'],
  '173': ['afetação', 'aparência', 'contrafação', 'disfarce', 'dissimulação', 'fingimento', 'simulação'],
  '174': ['afetivo', 'afetuoso'],
  '175': ['afetos', 'paixões'],
  '176': ['afetuoso', 'apaixonado'],
  '177': ['aferventar', 'aquentar', 'cozer', 'ferver'],
  '178': ['afinidade', 'analogia', 'conexão', 'relação'],
  '179': ['aderência', 'adesão', 'afinidade', 'atração', 'coerência', 'coesão', 'gravidade', 'gravitação', 'inerência'],
  '180': ['afim', 'afinidade', 'agnação', 'cognato', 'cognação', 'consanguinidade', 'ágnato'],
  '181': [
    'afirmar',
    'assegurar',
    'asseverar',
    'atestar',
    'certificar',
    'comprovar',
    'confirmar',
    'corroborar',
    'demonstrar',
    'dizer',
    'garantir',
    'ratificar',
  ],
  '182': [
    'afixar',
    'aplicar',
    'apor',
    'atar',
    'chumbar',
    'colar',
    'fixar',
    'grudar',
    'ligar',
    'pegar',
    'pregar',
    'prender',
    'segurar',
    'sobrepor',
    'soldar',
  ],
  '183': ['aflição', 'desgosto', 'espanhol', 'mágoa', 'pesadumbre', 'pesadume', 'pesar', 'tristeza'],
  '184': ['afluência', 'concorrência', 'concurso'],
  '185': ['afora', 'exceto'],
  '186': ['afiado', 'agudo', 'aguçado', 'amolado', 'cortante', 'incisivo', 'talhante'],
  '187': [
    'afoito',
    'animoso',
    'arrebatado',
    'arriscado',
    'arrojado',
    'atrevido',
    'audacioso',
    'audaz',
    'bravo',
    'confiado',
    'corajoso',
    'decidido',
    'desafrontado',
    'destemido',
    'determinado',
    'heroico',
    'impertérrito',
    'imponderado',
    'impávido',
    'inconsiderado',
    'intemente',
    'intrépido',
    'ousado',
    'resoluto',
    'temerário',
    'valente',
    'valoroso',
  ],
  '188': ['afronta', 'agravo', 'injúria', 'ofensa', 'ultraje'],
  '189': ['afrontar', 'arrostar', 'encarar'],
  '190': ['brequefeste', 'bródio', 'comezaina', 'janta', 'patuscada', 'pândega', 'rega-bofe', 'ágape'],
  '191': ['agonizar', 'estertorar'],
  '192': ['agradecido', 'cativo', 'grato', 'obrigado', 'penhorado', 'reconhecido'],
  '193': ['agreste', 'campesino', 'campestre', 'rústico'],
  '194': ['agrário', 'agrícola', 'rural', 'rústico'],
  '195': ['agricultor', 'agricultura', 'agronomia'],
  '196': ['aguardar', 'esperar'],
  '197': ['aguar', 'banhar', 'irrigar', 'molhar', 'regar'],
  '198': ['agudeza', 'agudo', 'penetrante', 'penetração', 'perspicaz', 'perspicácia', 'sagacidade'],
  '199': ['aguentar', 'suspender', 'sustentar', 'suster'],
  '200': ['aio', 'amo', 'instrutor', 'mestre', 'preceptor'],
  '201': ['airosidade', 'airoso', 'nobre', 'nobreza'],
  '202': [
    'agilidade',
    'destreza',
    'destro',
    'expedito',
    'expediência',
    'lesto',
    'ligeireza',
    'ligeiro',
    'lépido',
    'ágil',
  ],
  '203': ['agiota', 'onzeneiro', 'onzenário', 'usurário'],
  '204': ['agitação', 'insurreição', 'rebelião', 'revolta'],
  '205': ['agitar', 'aventar', 'controverter', 'debater', 'discutir', 'disputar', 'tratar', 'ventilar'],
  '206': ['ajuizado', 'assisado', 'cordato', 'grave', 'judicioso', 'prudente', 'sensato', 'sisudo', 'sábio'],
  '207': ['ala', 'fila', 'fileira', 'linha', 'renque', 'série'],
  '208': ['alarde', 'alardear', 'jactar-se', 'jactância', 'ostentar', 'ostentação', 'vangloriar-se'],
  '209': ['alargar', 'ampliar', 'dilatar'],
  '210': ['alarido', 'algazarra', 'berreiro', 'bramido', 'celeuma', 'clamor', 'gritaria', 'tumulto', 'vozeria'],
  '211': ['alarme', 'chamada', 'chamamento', 'rebate'],
  '212': ['alarme', 'medo', 'susto', 'temor', 'terror'],
  '213': ['albergaria', 'albergue', 'estalagem', 'guarida', 'hospedaria', 'hotel', 'pensão', 'pousada'],
  '214': ['albescente', 'alvacento', 'alvadio', 'esbranquiçado'],
  '215': ['alcácer', 'alcáçar', 'palácio', 'paço'],
  '216': ['alcançar', 'conseguir', 'gozar', 'impetrar', 'lograr', 'obter'],
  '217': ['alcançar', 'atingir', 'chegar', 'tocar'],
  '218': ['alcance', 'desfalque', 'irregularidade'],
  '219': ['alcantil', 'despenhadeiro', 'ribanceira'],
  '220': ['alçar', 'elevar', 'erguer', 'levantar'],
  '221': ['alcateia', 'bando', 'enxame', 'multidão'],
  '222': ['alcatifa', 'alfombra', 'tapete', 'tapeçaria'],
  '223': ['alcoice', 'bordel', 'lupanar', 'prostíbulo'],
  '224': ['alcunha', 'apelido', 'nome', 'sobrenome'],
  '225': ['alegar', 'citar'],
  '226': ['alacridade', 'alegria', 'contentamento', 'exultação', 'jovialidade', 'júbilo', 'ledice', 'regozijo'],
  '227': ['aleive', 'aleivosia', 'aleivoso', 'caluniador', 'calunioso', 'calúnia', 'traiçoeiro', 'traição'],
  '228': ['adiante', 'além', 'após', 'depois'],
  '229': ['alentado', 'forte', 'robusto', 'vigoroso'],
  '230': ['alfanje', 'chanfalho', 'cimitarra', 'durindana', 'espada', 'gládio', 'montante', 'sabre', 'terçado'],
  '231': ['afinal', 'alfim', 'enfim', 'finalmente', 'por'],
  '232': ['algoz', 'carnífice', 'carrasco', 'executor', 'sacrificador', 'verdugo'],
  '233': ['alguns', 'certos'],
  '234': ['alheio', 'de outrem', 'estranho'],
  '235': ['algures', 'alhures'],
  '236': ['acolá', 'ali', 'além', 'aí', 'lá'],
  '237': ['aliança', 'coalizão', 'confederação', 'liga'],
  '238': ['aliança', 'casamento', 'consórcio', 'união'],
  '239': ['alicerce', 'base', 'embasamento', 'fundamento', 'peanha', 'pedestal'],
  '240': ['aliciar', 'corromper', 'engodar', 'peitar', 'seduzir', 'subornar'],
  '241': ['alienar', 'cambiar', 'escambiar', 'permutar', 'traficar', 'trocar', 'vender'],
  '242': ['alimentar', 'manter', 'nutrir', 'sustentar'],
  '243': ['alimpa', 'monda', 'poda'],
  '244': ['alistar', 'arrolar', 'catalogar', 'relacionar'],
  '245': [
    'alcofa',
    'alforje',
    'aljava',
    'açafate',
    'bolsa',
    'bruaca',
    'carcás',
    'cesta',
    'estojo',
    'guaiaca',
    'mala',
    'mochila',
    'peçuelo',
    'picoá',
    'saco',
    'seira',
    'seirão',
  ],
  '246': ['frio', 'frígido', 'gelado', 'glacial', 'gélido', 'regelado', 'álgido'],
  '247': ['alma', 'coração', 'espírito', 'eu', 'ânimo'],
  '248': [
    'almanaque',
    'anuário',
    'calendário',
    'folhinha',
    'guia',
    'indicador',
    'manual',
    'prontuário',
    'repertório',
    'roteiro',
    'vademeco',
  ],
  '249': ['almejar', 'ambicionar', 'aspirar', 'desejar'],
  '250': ['almo', 'criador', 'nutriente', 'nutritivo'],
  '251': [
    'alocução',
    'arenga',
    'arrazoamento',
    'discurso',
    'fala',
    'homilia',
    'oração',
    'panegírico',
    'proclamação',
    'prática',
    'prédica',
    'sermão',
  ],
  '252': ['adro', 'alpendrada', 'alpendre', 'pórtico', 'telheiro', 'vestíbulo', 'átrio'],
  '253': ['altaneria', 'altivez', 'empáfia', 'fatuidade', 'impostura', 'orgulho', 'soberba', 'sobranceria'],
  '254': ['alternativa', 'dilema', 'disjuntiva'],
  '255': ['altitude', 'altura'],
  '256': ['alteza', 'altura'],
  '257': ['alterar', 'modificar', 'mudar', 'reformar', 'remodelar', 'renovar', 'transformar', 'variar'],
  '258': ['alucinar', 'cegar', 'confundir', 'ofuscar'],
  '259': [
    'alucinado',
    'atordoado',
    'aturdido',
    'cego',
    'delirante',
    'demente',
    'desvairado',
    'doido',
    'estonteado',
    'insano',
    'insensato',
    'louco',
    'perdido',
  ],
  '260': ['aludir', 'enunciar', 'expor', 'indicar', 'mencionar', 'referir'],
  '261': ['alusivo', 'concernente', 'referente', 'relativo', 'respetivo'],
  '262': ['alquilar', 'alugar', 'arrendar', 'locar', 'sublocar'],
  '263': ['aluno', 'discípulo', 'educando'],
  '264': ['albor', 'alva', 'alvor', 'alvorada', 'aurora', 'crepúsculo', 'dilúculo', 'madrugada'],
  '265': ['alvo', 'escopo', 'fim', 'fito', 'intento', 'intenção', 'mira', 'objeto', 'propósito'],
  '266': ['centro', 'cerne', 'imo', 'interior', 'meio', 'profundeza', 'recesso', 'seio', 'âmago', 'íntimo'],
  '267': ['abater', 'abrandar', 'acalmar', 'afrouxar', 'amainar', 'diminuir', 'enfraquecer', 'sossegar'],
  '268': ['amansar', 'domar', 'domesticar'],
  '269': ['amante', 'amásia', 'barregã', 'concubina'],
  '270': ['amachucar', 'amarfanhar', 'amarrotar', 'amassar', 'enrugar', 'machucar', 'marlotar'],
  '271': ['ambição', 'avareza', 'avidez', 'cobiça', 'cupidez', 'gana', 'ganância'],
  '272': ['ambíguo', 'anfibológico', 'confuso', 'duvidoso', 'dúbio', 'equívoco', 'impreciso', 'incerto'],
  '273': ['recinto', 'área', 'âmbito'],
  '274': ['ambos', 'os dois', 'outro', 'um'],
  '275': ['ambulante', 'errante', 'nômade', 'perdido', 'peregrino', 'teatino', 'vagabundo', 'vagante'],
  '276': ['ameaçar', 'amedrontar', 'assustar', 'atemorizar', 'intimidar'],
  '277': ['agradável', 'ameno', 'aprazível', 'delicioso'],
  '278': ['abolar', 'amassar', 'amolgar', 'amossar'],
  '279': ['acumular', 'ajuntar', 'amontoar', 'reunir'],
  '280': ['amostra', 'indício', 'mostra', 'prova', 'sinal'],
  '281': ['amplidão', 'amplitude', 'extensão', 'grandeza', 'imensidade', 'imensidão', 'vastidão'],
  '282': ['anacoreta', 'cenobita', 'eremita', 'solitário'],
  '283': ['análise', 'epítome', 'extrato', 'resumo'],
  '284': [
    'anarquia',
    'balbúrdia',
    'caos',
    'cizânia',
    'confusão',
    'desconcerto',
    'desgoverno',
    'desordem',
    'desregramento',
    'discórdia',
  ],
  '285': ['amaldiçoar', 'anatematizar', 'anátema', 'excomungar', 'excomunhão', 'maldição'],
  '286': ['anatomia', 'autópsia', 'dissecção'],
  '287': ['ancião', 'velho'],
  '288': ['ansiedade', 'ânsia'],
  '289': ['andaço', 'contágio', 'endemia', 'epidemia'],
  '290': ['andar', 'caminhar', 'ir', 'marchar', 'seguir'],
  '291': ['andrajos', 'farrapos', 'molambos', 'trapos'],
  '292': ['anexado', 'anexar', 'anexação', 'anexo', 'incorporado', 'incorporar', 'incorporação'],
  '293': ['anexo', 'dependente', 'unido'],
  '294': ['aliciar', 'angariar', 'recrutar'],
  '295': ['angu', 'mexido', 'mingau', 'pirão', 'revirado'],
  '296': ['anelo', 'anseio', 'aspiração', 'desejo', 'vontade'],
  '297': ['anoitecer', 'enoitecer'],
  '298': ['anomalia', 'anormal', 'anormalidade', 'anômalo', 'excepcional', 'excepcionalidade'],
  '299': ['anoso', 'antigo', 'idoso', 'secular', 'velho'],
  '300': ['anotar', 'anotações', 'comentar', 'notas'],
  '301': ['anuviar', 'carregar', 'ensombrar', 'escurecer', 'nublar', 'obcecar', 'obscurecer', 'toldar'],
  '302': ['antártico', 'austral', 'meridional'],
  '303': ['antecedente', 'anterior', 'precedente'],
  '304': ['antecedentes', 'precedentes'],
  '305': ['antecessor', 'predecessor'],
  '306': ['antecessores', 'antepassados', 'antigos', 'ascendentes', 'avoengos', 'avós', 'maiores', 'pais'],
  '307': ['adiantadamente', 'antecipadamente'],
  '308': ['antemural', 'muralha', 'muro'],
  '309': ['antipatia', 'aversão', 'repugnância', 'ódio'],
  '310': ['antiquado', 'arcaico', 'desusado', 'obsoleto'],
  '311': ['antiquário', 'arqueólogo'],
  '312': ['antilogia', 'antinomia', 'antífrase', 'antítese', 'contradição', 'contrariedade', 'contraste'],
  '313': ['antro', 'caverna', 'cova', 'furna', 'gruta', 'lapa'],
  '314': ['aparato', 'aparelho', 'apresto', 'preparativo'],
  '315': [
    'alardo',
    'aparato',
    'esplendor',
    'fausto',
    'grandeza',
    'luxo',
    'magnificência',
    'majestade',
    'ostentação',
    'pompa',
    'sumptuosidade',
  ],
  '316': ['aparecimento', 'aparição'],
  '317': ['aparência', 'ar', 'ares', 'aspeto', 'exterior', 'exterioridade', 'mostra', 'semblante', 'visos'],
  '318': ['apedrejar', 'lapidar'],
  '319': ['agravo', 'apelação', 'recurso'],
  '320': ['apenas', 'exclusivamente', 'somente', 'só'],
  '321': ['apêndice', 'suplemento'],
  '322': ['apertado', 'estreito'],
  '323': ['cimo', 'cume', 'cumeada', 'cumeeira', 'ápice'],
  '324': ['apócrifo', 'fictício', 'pretenso', 'suposto'],
  '325': ['apologia', 'defesa', 'elogio', 'justificação'],
  '326': ['aposentar', 'jubilar', 'reformar'],
  '327': ['apossar-se', 'apropriar-se', 'conquistar', 'invadir', 'usurpar'],
  '328': ['apóstolo', 'evangelizador', 'missionário'],
  '329': ['apreço', 'consideração', 'conta', 'estima'],
  '330': ['apreender', 'apresar', 'arrestar', 'prender'],
  '331': ['aparecer', 'apresentar-se', 'comparecer'],
  '332': ['aprisco', 'curral', 'mangueira', 'redil'],
  '333': ['aprofundar', 'profundar'],
  '334': [
    'aptidão',
    'capacidade',
    'disposição',
    'gosto',
    'habilidade',
    'idoneidade',
    'inclinação',
    'jeito',
    'propensão',
    'talento',
    'vocação',
  ],
  '335': ['aqui', 'cá'],
  '336': ['ardil', 'armadilha', 'arteirice', 'astúcia', 'cilada', 'emboscada', 'estratagema', 'logro'],
  '337': [
    'custoso',
    'dificultoso',
    'difícil',
    'doloroso',
    'espinhoso',
    'fatigante',
    'intrincado',
    'penoso',
    'trabalhoso',
    'árduo',
    'ímprobo',
  ],
  '338': ['superfície', 'área'],
  '339': ['aridez', 'estéril', 'seco', 'sequidade', 'árido'],
  '340': ['armada', 'esquadra', 'esquadrilha', 'frota'],
  '341': ['armistício', 'suspensão de armas', 'tréguas'],
  '342': ['aroma', 'aromas', 'fragrância', 'perfume'],
  '343': ['arrancar', 'arrebatar', 'extrair', 'sacar', 'tirar'],
  '344': ['arrependimento', 'pesar', 'remorso'],
  '345': ['arroio', 'regato', 'regueiro', 'ribeira', 'ribeiro'],
  '346': ['arte', 'artificial', 'artifício', 'artístico'],
  '347': ['arte', 'mister', 'ofício', 'profissão – “posto'],
  '348': ['arte', 'ciência'],
  '349': ['artesano', 'artesão', 'artista', 'artífice'],
  '350': ['boreal', 'norte', 'setentrional', 'ártico'],
  '351': ['articular', 'dizer', 'proferir', 'pronunciar'],
  '352': ['artificial', 'factício', 'falso', 'ficto', 'fictício', 'fingido', 'simulado'],
  '353': ['artificial', 'artificioso'],
  '354': ['artefacto', 'artifício'],
  '355': ['brasa', 'áscua'],
  '356': ['assassinar', 'massacrar', 'matar', 'trucidar'],
  '357': [
    'assassinato',
    'assassino',
    'assassínio',
    'homicida',
    'homicídio',
    'matador',
    'matança',
    'morte',
    'morticínio',
  ],
  '358': ['assaz', 'bastante', 'suficiente'],
  '359': ['assédio', 'bloqueio', 'cerco', 'sítio'],
  '360': ['assíduo', 'frequente'],
  '361': ['assinar', 'firmar', 'subscrever'],
  '362': ['assoante', 'assonância', 'consoante', 'consonância', 'rima', 'rimado'],
  '363': ['assunto', 'matéria', 'objeto'],
  '364': ['astrologia', 'astronomia'],
  '365': ['assento', 'ata', 'auto', 'registro', 'termo'],
  '366': ['ataúde', 'caixão', 'esquife', 'féretro', 'tumba'],
  '367': [
    'ateu',
    'cético',
    'descrente',
    'descrido',
    'gentil',
    'gentio',
    'idólatra',
    'incrédulo',
    'incréu',
    'infiel',
    'irreligioso',
    'pagão',
    'sacrílego',
    'ímpio',
  ],
  '368': ['apercepção', 'aplicação', 'atenção', 'contensão', 'meditação', 'ponderação', 'reflexão'],
  '369': [
    'atentado',
    'crime',
    'culpa',
    'delito',
    'falta',
    'infração',
    'pecado',
    'quebra',
    'quebrantamento',
    'tentativa',
    'transgressão',
    'violação',
  ],
  '370': ['atitude', 'gesto', 'posição', 'postura'],
  '371': [
    'afadigado',
    'afanoso',
    'ansioso',
    'apressurado',
    'ativo',
    'cuidadoso',
    'desvelado',
    'diligente',
    'experto',
    'moirejante',
    'pressuroso',
    'solerte',
    'solícito',
    'zeloso',
  ],
  '372': ['ativo', 'eficaz', 'enérgico', 'forte', 'violento'],
  '373': ['artista', 'ator', 'comediante', 'cômico'],
  '374': ['atribuir', 'imputar'],
  '375': ['atributo', 'predicado', 'propriedade', 'qualidade'],
  '376': ['agora', 'atual', 'atualmente', 'hoje', 'presente', 'presentemente'],
  '377': ['agir', 'atuar', 'influir', 'obrar', 'operar'],
  '378': ['aguentar', 'aturar', 'padecer', 'sofrer', 'suportar', 'tolerar'],
  '379': ['atordoar', 'aturdir', 'conturbar', 'perturbar'],
  '380': ['augusto', 'glorioso', 'grandioso', 'imponente', 'majestoso', 'pontifical', 'soberano', 'solene'],
  '381': ['ampliar-se', 'amplificar-se', 'aumentar', 'avolumar-se', 'avultar', 'crescer', 'engrandecer'],
  '382': ['aragem', 'aura', 'brisa', 'favônio', 'viração', 'zéfiro'],
  '383': ['auspícios', 'patrocínio', 'proteção', 'salvaguarda'],
  '384': ['auspicioso', 'esperançoso', 'prometedor'],
  '385': ['austero', 'duro', 'inabalável', 'inexorável', 'inflexível', 'rigoroso', 'rígido', 'ríspido', 'severo'],
  '386': ['autêntico', 'formal', 'solene'],
  '387': ['autonomia', 'independência', 'soberania'],
  '388': ['autor', 'escritor', 'publicista'],
  '389': ['autoridade', 'força', 'poder', 'potestade'],
  '390': ['apreciar', 'apreçar', 'apreçar', 'avaliar'],
  '391': ['avarento', 'avaro', 'fona', 'sovina', 'ávido'],
  '392': ['avaria', 'estrago', 'lesão', 'perda', 'prejuízo'],
  '393': ['ave', 'pássaro', 'volátil'],
  '394': ['averiguar', 'constatar', 'reconhecer', 'verificar'],
  '395': ['anverso', 'avesso', 'inverso', 'reverso', 'verso'],
  '396': ['avistar', 'bispar', 'descobrir', 'devisar', 'discernir', 'distinguir', 'enxergar', 'lobrigar', 'ver'],
  '397': ['avivar', 'aviventar'],
  '398': ['azado', 'conveniente', 'oportuno', 'próprio'],
  '399': ['agoirento', 'aziago', 'funesto', 'infausto', 'nefasto'],
  '400': ['bailado', 'baile', 'dança', 'fandango', 'folgança', 'folia', 'jongo', 'samba'],
  '401': ['bala', 'projetil'],
  '402': ['balancear', 'balançar', 'duvidar', 'embalançar', 'hesitar', 'vacilar'],
  '403': ['balbuciar', 'gaguejar', 'tartamudear'],
  '404': ['banal', 'comum', 'ordinário', 'trivial', 'vulgar'],
  '405': ['bancarrota', 'falência', 'quebra'],
  '406': ['banda', 'charanga', 'fanfarra', 'filarmônica', 'música', 'orquestra'],
  '407': ['bandeira', 'estandarte', 'insígnia', 'pavilhão', 'vexilo'],
  '408': ['bandido', 'bandoleiro', 'celerado', 'facínora', 'malfeitor', 'salteador'],
  '409': ['banir', 'degredar', 'deportar', 'desterrar', 'exilar', 'expatriar', 'proscrever'],
  '410': ['barbaridade', 'crueldade', 'crueza', 'desumanidade', 'fereza', 'ferocidade'],
  '411': ['barbarismo', 'solecismo'],
  '412': ['bárbaro', 'selvagem'],
  '413': ['barco', 'embarcação', 'fragata', 'nau', 'navio'],
  '414': ['bardo', 'rapsoda', 'trovador', 'vate'],
  '415': ['bastardo', 'espúrio', 'ilegítimo', 'natural'],
  '416': ['batologia', 'redundância', 'tautologia'],
  '417': ['beato', 'carola', 'hipócrita', 'tartufo'],
  '418': ['beiço', 'lábio'],
  '419': ['belicoso', 'bélico', 'guerreiro', 'marcial', 'militar'],
  '420': ['beneficência', 'caridade', 'filantropia'],
  '421': ['benefício', 'favor', 'graça', 'mercê', 'obséquio'],
  '422': ['biblioteca', 'livraria'],
  '423': ['bispado', 'diocese', 'episcopado', 'mitra'],
  '424': ['boiar', 'flutuar', 'nadar', 'sobrenadar'],
  '425': ['bala', 'bola', 'esfera', 'globo', 'pelouro'],
  '426': ['bolha', 'borbulha', 'empola', 'vesícula'],
  '427': ['borbotão', 'cachão', 'golfada', 'gorgolhão', 'jacto', 'jorro', 'torrente'],
  '428': ['borda', 'margem', 'riba', 'ribança', 'ribeira'],
  '429': ['bastão', 'bordão', 'cajado', 'pau', 'varapau'],
  '430': ['aguaceiro', 'borrasca', 'procela', 'refrega', 'tempestade', 'temporal', 'tormenta', 'vendaval'],
  '431': [
    'arvoredo',
    'bosque',
    'capoeira',
    'capão',
    'floresta',
    'luco',
    'mata',
    'restinga',
    'selva',
    'sertão',
    'tapera',
  ],
  '432': ['bossa', 'corcova', 'corcunda', 'giba', 'gibosidade'],
  '433': ['botão', 'broto', 'gema', 'gomo', 'olho', 'rebento', 'renovo'],
  '434': ['botica', 'farmácia'],
  '435': ['bota', 'botim', 'botina', 'calçado', 'sapato'],
  '436': ['breve', 'conciso', 'curto', 'lacônico', 'preciso', 'sucinto'],
  '437': ['brilhante', 'diamante'],
  '438': [
    'brilhar',
    'cintilar',
    'esplender',
    'fulgurar',
    'luzir',
    'rebrilhar',
    'reluzir',
    'resplandecer',
    'resplendecer',
    'resplender',
    'transluzir',
    'tremeluzir',
  ],
  '439': ['brinde', 'dom', 'donativo', 'dádiva', 'presente'],
  '440': ['bruma', 'caligem', 'nevoeiro', 'nuvem', 'névoa'],
  '441': ['bufo', 'bufão', 'burlesco', 'cômico', 'grotesco'],
  '442': ['buscar', 'procurar'],
  '443': ['cabeleira', 'cabelo', 'coma', 'grenha', 'guedelha', 'madeixa', 'marrafa', 'melena'],
  '444': ['cabedelo', 'cabo', 'pontal', 'promontório'],
  '445': ['cachoeira', 'cascata', 'catadupa', 'catarata', 'corredeira', 'rápido', 'salto'],
  '446': ['cadafalso', 'forca', 'guilhotina', 'patíbulo'],
  '447': [
    'caducidade',
    'caduco',
    'caduquice',
    'decrepitude',
    'decrépito',
    'invalidez',
    'inválido',
    'senectude',
    'senilidade',
    'velhice',
    'velho',
  ],
  '448': ['calado', 'mudo', 'silencioso', 'taciturno'],
  '449': ['calcular', 'computar', 'contar', 'cálculo'],
  '450': [
    'atalho',
    'azinhaga',
    'caminho',
    'carreiro',
    'estrada',
    'picada',
    'raia',
    'senda',
    'trilha',
    'vereda',
    'via',
    'vicina',
  ],
  '451': ['cansaço', 'canseira', 'fadiga', 'lassidão'],
  '452': ['canto', 'canção', 'cântico', 'hino'],
  '453': ['arguto', 'capcioso', 'insidioso', 'sofístico'],
  '454': ['capitulação', 'rendição'],
  '455': ['cabido', 'capítulo'],
  '456': ['cara', 'face', 'frente', 'fronte', 'rosto', 'semblante', 'vulto'],
  '457': ['caráter', 'compleição', 'constituição', 'gênio', 'humor', 'natural', 'temperamento', 'índole'],
  '458': ['arcaboiço', 'carcaça', 'esqueleto'],
  '459': ['carecer', 'necessitar', 'precisar'],
  '460': [
    'carestia',
    'careza',
    'carência',
    'escassez',
    'fome',
    'indigência',
    'inópia',
    'miséria',
    'necessidade',
    'penúria',
    'pobreza',
    'sede',
  ],
  '461': ['cargo', 'emprego', 'encargo', 'ministério'],
  '462': ['caridoso', 'caritativo'],
  '463': ['carniceiro', 'carnívoro'],
  '464': ['bilhete', 'carta', 'epístola', 'missiva'],
  '465': ['casa', 'morada', 'palacete', 'palácio', 'vivenda'],
  '466': ['caso', 'circunstância', 'conjuntura', 'situação'],
  '467': [
    'castidade',
    'casto',
    'continente',
    'continência',
    'ilibado',
    'impoluto',
    'incorrupto',
    'intemerato',
    'pureza',
    'puro',
    'virgem',
    'virgindade',
  ],
  '468': ['castigar', 'castigo', 'pena', 'punir', 'punição'],
  '469': ['catálogo', 'lista', 'nomenclatura', 'rol'],
  '470': ['cativeiro', 'cativo', 'escravidão', 'escravo'],
  '471': ['causa', 'motivo', 'móvel', 'pretexto', 'razão'],
  '472': ['causticante', 'cáustico', 'irônico', 'mordaz', 'mordente', 'pungente', 'pungitivo', 'satírico'],
  '473': ['cegamente', 'às cegas'],
  '474': ['celebrar', 'comemorar', 'festejar', 'rememorar', 'solenizar'],
  '475': ['celeste', 'celestial', 'célico', 'divinal', 'divino'],
  '476': ['celibatário', 'solteiro'],
  '477': [
    'campa',
    'carneiro',
    'catacumbas',
    'cenotáfio',
    'cova',
    'hipogeu',
    'jazigo',
    'mausoléu',
    'monumento',
    'sarcófago',
    'sepulcro',
    'sepultura',
    'túmulo',
  ],
  '478': ['admoestação', 'censura', 'crítica', 'sátira'],
  '479': ['cerimônia', 'liturgia', 'rito', 'ritual'],
  '480': ['chama', 'chispa', 'fagulha', 'faísca', 'flama', 'fogo', 'fogueira', 'incêndio', 'labareda', 'lume'],
  '481': ['atrativo', 'chamariz', 'engodo', 'isca', 'negaça', 'reclamo'],
  '482': ['chapada', 'esplanada', 'planalto', 'planura'],
  '483': ['cheia', 'dilúvio', 'enchente', 'inundação'],
  '484': ['chistoso', 'espirituoso', 'faceto', 'gracioso'],
  '485': ['chocalheiro', 'chocarreiro', 'garabulho', 'linguareiro', 'linguarudo', 'pernóstico'],
  '486': ['chocar', 'incubar'],
  '487': ['chocar', 'melindrar', 'ofender'],
  '488': ['choque', 'conflito', 'embate', 'encontro'],
  '489': ['carpir', 'chorar', 'gemer', 'lagrimar', 'lamentar', 'prantear', 'soluçar'],
  '490': ['castelo', 'cidade fortificada', 'cidadela', 'fortaleza', 'forte', 'fortim', 'praça'],
  '491': ['cifra', 'nada', 'zero'],
  '492': ['boêmio', 'cigano', 'vagabundo', 'valdevino'],
  '493': ['cimentar', 'consolidar', 'firmar', 'prender'],
  '494': ['cínico', 'desavergonhado', 'descarado', 'despudorado', 'desvergonhado', 'impudente'],
  '495': ['apertar', 'cercar', 'cingir', 'circular', 'rodear'],
  '496': ['burilar', 'cinzelar', 'entalhar', 'esculpir', 'gravar', 'imprimir', 'lavorar', 'lavorear', 'lavrar'],
  '497': ['circunlocução', 'circunlóquio', 'perífrase'],
  '498': ['cioso', 'ciumento', 'ciúme', 'inveja', 'invejoso', 'zelo', 'zeloso'],
  '499': ['civil', 'cível'],
  '500': ['civil', 'cívico'],
  '501': ['civilização', 'cultura', 'instrução', 'polícia'],
  '502': ['civismo', 'cívico', 'patriotismo', 'patriótico'],
  '503': ['brilho', 'claridade', 'clarão', 'esplendor', 'fulgor', 'lampejo', 'luar', 'lume', 'luz'],
  '504': ['clareza', 'claridade', 'perspicuidade'],
  '505': ['claro', 'diáfano', 'perspícuo', 'translúcido', 'transparente'],
  '506': ['camada', 'categoria', 'classe', 'grupo', 'hierarquia', 'jerarquia'],
  '507': ['classe', 'espécie', 'família', 'gênero', 'ordem'],
  '508': ['arranjar', 'classificar', 'coordenar', 'dispor', 'distribuir', 'ordenar', 'separar'],
  '509': ['cláusula', 'frase', 'oração', 'período', 'proposição', 'sentença', 'trecho'],
  '510': [
    'benignidade',
    'bondade',
    'caridade',
    'clemência',
    'comiseração',
    'compaixão',
    'dó',
    'humanidade',
    'indulgência',
    'inocência',
    'miseração',
    'misericórdia',
    'pena',
    'piedade',
    'tolerância',
  ],
  '511': ['clérigo', 'eclesiástico', 'padre', 'presbítero', 'religioso', 'sacerdote'],
  '512': ['cliente', 'comitente', 'constituinte'],
  '513': ['clientela', 'clínica'],
  '514': ['coagir', 'constranger', 'forçar', 'obrigar'],
  '515': ['casca', 'cortiça', 'crosta', 'crusta', 'côdea'],
  '516': ['coetâneo', 'coevo', 'contemporâneo'],
  '517': ['camarada', 'coirmão', 'colega', 'companheiro', 'confrade', 'consócio'],
  '518': ['colossal', 'desabalado', 'enorme', 'gigantesco', 'monstruoso'],
  '519': ['coluna', 'esteio', 'pedestal', 'pilar', 'pilastra'],
  '520': ['coma', 'letargia', 'modorra', 'sopor', 'torpor'],
  '521': ['autoridade', 'comando', 'direção', 'governo', 'mando', 'ordem'],
  '522': ['começar', 'principiar'],
  '523': ['comédia', 'entremez', 'farsa', 'pantomima'],
  '524': ['comerciante', 'mercador', 'negociante'],
  '525': ['cometer', 'fazer', 'perpetrar', 'praticar'],
  '526': ['cometimento', 'empreendimento', 'empresa'],
  '527': ['comilão', 'faminto', 'glutão', 'guloso', 'voraz'],
  '528': ['assim como', 'como', 'do mesmo modo'],
  '529': ['compacto', 'denso', 'espesso'],
  '530': ['amiserar-se', 'apiedar-se', 'compadecer-se', 'condoer-se', 'enternecer-se'],
  '531': ['associação', 'companhia', 'sindicato', 'sociedade'],
  '532': ['colacionar', 'comparar', 'conferir', 'confrontar', 'cotejar'],
  '533': ['compartilhar', 'compartir', 'participar', 'partilhar'],
  '534': ['compassado', 'lento', 'tardio', 'vagaroso'],
  '535': ['compatriota', 'compatrício', 'patrício'],
  '536': ['compensar', 'indenizar', 'reparar', 'ressarcir'],
  '537': ['compensar', 'contrabalançar', 'igualar'],
  '538': ['competição', 'competência'],
  '539': ['capacidade', 'competência'],
  '540': ['adequado', 'competente', 'próprio', 'respetivo'],
  '541': ['competir', 'concorrer', 'emular', 'rivalizar'],
  '542': ['acabamento', 'complemento', 'completação', 'conclusão', 'implemento', 'suplemento'],
  '543': ['complexo', 'complicado', 'implexo', 'implicado'],
  '544': ['compreender', 'conceber', 'entender'],
  '545': ['comum', 'geral', 'público'],
  '546': ['comumente', 'de ordinário', 'de regra', 'em regra', 'geralmente', 'ordinariamente'],
  '547': ['comuna', 'concelho', 'município'],
  '548': ['conceder', 'outorgar'],
  '549': ['conceito', 'juízo', 'opinião'],
  '550': ['compreensão', 'concepção', 'entendimento', 'intelecto', 'inteligência', 'mente', 'razão'],
  '551': ['açular', 'concitar', 'induzir', 'instigar', 'insuflar', 'provocar'],
  '552': ['coligir', 'concluir', 'deduzir', 'induzir', 'inferir'],
  '553': ['conclusão', 'consequência', 'indução'],
  '554': [
    'concupiscência',
    'lascívia',
    'libidinagem',
    'lubricidade',
    'luxúria',
    'moleza',
    'molícia',
    'sensualidade',
    'voluptuosidade',
    'volúpia',
  ],
  '555': ['conferência', 'entrevista'],
  '556': ['certeza', 'confiança', 'fé'],
  '557': ['confiança', 'segurança', 'seguridade'],
  '558': ['configuração', 'conformação', 'figura'],
  '559': ['apenar', 'apreender', 'arrestar', 'confiscar', 'embargar', 'penhorar', 'sequestrar'],
  '560': ['conforme', 'segundo'],
  '561': ['confortar', 'consolar'],
  '562': ['confraria', 'congregação', 'irmandade', 'ordem'],
  '563': ['confutar', 'impugnar', 'rebater', 'refutar'],
  '564': ['conjugal', 'matrimonial', 'nupcial'],
  '565': ['consorte', 'cônjuge', 'esposo', 'marido', 'mulher', 'senhora'],
  '566': ['conivente', 'conivência', 'cumplicidade'],
  '567': ['consagrar', 'dedicar', 'oferecer', 'ofertar'],
  '568': ['cabala', 'conjuração', 'conluio', 'conspiração', 'enredo', 'intriga', 'mexerico', 'trama'],
  '569': ['construir', 'edificar', 'fabricar', 'fazer'],
  '570': [
    'constante',
    'fiel',
    'firme',
    'forte',
    'inabalável',
    'inalterável',
    'inflexível',
    'leal',
    'obstinado',
    'perseverante',
    'persistente',
    'teimoso',
    'tenaz',
  ],
  '571': ['contestável', 'duvidoso', 'hipotético', 'incerto', 'problemático'],
  '572': ['contribuição', 'derrama', 'direitos', 'finta', 'imposto', 'páreas', 'subsídios', 'taxa', 'tributo'],
  '573': ['contubérnio', 'convivência', 'convívio'],
  '574': ['conveniente', 'decente', 'decoroso', 'discreto', 'honesto'],
  '575': ['conferência', 'conversa', 'conversação'],
  '576': ['convicção', 'persuasão'],
  '577': ['certo', 'convincente', 'evidente', 'incontestável', 'indubitável', 'persuasivo', 'persuasório', 'suasório'],
  '578': ['convir', 'cumprir', 'importar', 'relevar'],
  '579': ['comensal', 'convidado', 'conviva'],
  '580': ['coonestar', 'justificar'],
  '581': ['colaborar', 'cooperar'],
  '582': ['calcar', 'colar', 'copiar', 'decalcar', 'plagiar', 'transcrever', 'trasladar'],
  '583': ['abundante', 'copioso', 'muito', 'numeroso'],
  '584': ['coroa', 'diadema'],
  '585': ['castiço', 'clássico', 'correto', 'correção', 'exato', 'lídimo', 'perfeito', 'puro', 'vernáculo'],
  '586': ['corso', 'corsário', 'flibusteiro', 'pirata', 'pirataria'],
  '587': ['corte', 'fio', 'gume'],
  '588': ['cosmogonia', 'cosmografia', 'cosmologia'],
  '589': ['costume', 'hábito', 'rotina', 'uso'],
  '590': ['covarde', 'fraco', 'poltrão', 'pusilânime'],
  '591': ['crápula', 'deboche', 'libertinagem', 'orgia'],
  '592': ['crasso', 'grosseiro', 'palmar'],
  '593': ['criar', 'gerar', 'produzir'],
  '594': ['crebro', 'frequente', 'reiterado', 'repetido'],
  '595': ['crença', 'fé', 'opinião'],
  '596': ['crer', 'julgar', 'pensar', 'presumir', 'supor'],
  '597': ['antologia', 'coletânea', 'coleção', 'crestomatia', 'florilégio', 'polianteia', 'seleta', 'silva'],
  '598': ['cultivo', 'cultura'],
  '599': ['cumprir', 'guardar', 'observar'],
  '600': ['dama', 'dona', 'matrona', 'mulher', 'senhora'],
  '601': ['danoso', 'nocivo', 'pernicioso', 'prejudicial'],
  '602': ['dar', 'doar', 'dom', 'donativo', 'dote', 'dádiva'],
  '603': ['debilitado', 'débil', 'enfraquecido', 'fraco'],
  '604': ['bosquejo', 'debuxo', 'esboceto', 'esboço'],
  '605': ['decair', 'descair'],
  '606': ['decapitar', 'degolar', 'descabeçar', 'guilhotinar'],
  '607': ['decoro', 'decência', 'dignidade', 'gravidade', 'honor', 'honra', 'pudor', 'recato', 'reserva'],
  '608': ['decepção', 'desengano', 'desilusão'],
  '609': ['codilho', 'decepção', 'engano', 'ilusão', 'logro', 'surpresa'],
  '610': [
    'anunciar',
    'declarar',
    'descobrir',
    'desvendar',
    'divulgar',
    'expor',
    'manifestar',
    'noticiar',
    'patentear',
    'promulgar',
    'publicar',
    'revelar',
  ],
  '611': ['analisar', 'anatomizar', 'decompor', 'destrinçar', 'dissecar', 'escalpelar', 'esmiuçar', 'examinar'],
  '612': ['aviso', 'decreto', 'lei', 'resolução'],
  '613': ['defeito', 'deformidade', 'imperfeição'],
  '614': ['defender', 'justificar'],
  '615': ['defender', 'estorvar', 'impedir', 'inibir', 'interditar', 'interdizer', 'obstar', 'proibir', 'vedar'],
  '616': ['decidir', 'deliberar', 'opinar', 'resolver', 'votar'],
  '617': ['delicadeza', 'delicado', 'fineza', 'fino', 'finura', 'leve', 'subtil', 'subtileza', 'tênue'],
  '618': ['acusado', 'criminoso', 'delinquente', 'réu'],
  '619': ['demo', 'demônio', 'diabo', 'diacho', 'satã'],
  '620': ['deplorável', 'lamentável', 'lastimável'],
  '621': ['depois', 'logo'],
  '622': ['demitir', 'depor', 'destituir', 'dispensar'],
  '623': ['de repente', 'de súbito', 'repentinamente', 'subitamente'],
  '624': ['decorrer', 'derivar', 'proceder', 'provir', 'vir'],
  '625': ['derramar', 'entornar'],
  '626': ['derreter', 'dissolver', 'fundir', 'liquefazer'],
  '627': ['aniquilar', 'bater', 'derrotar', 'desbaratar', 'desfazer', 'destroçar', 'destruir', 'exterminar'],
  '628': ['agressivo', 'desabrido', 'hostil', 'violento'],
  '629': ['desaconselhar', 'desconvencer', 'desenganar', 'desiludir', 'despersuadir', 'dissuadir'],
  '630': ['desafio', 'duelo', 'provocação', 'repto'],
  '631': ['desandar', 'recuar', 'regressar', 'retornar', 'retroceder', 'retrogradar', 'tornar', 'voltar', 'volver'],
  '632': ['desapegar', 'despegar'],
  '633': ['desapercebido', 'despercebido'],
  '634': ['desarranjar', 'desordenar', 'transtornar'],
  '635': ['desarrugar', 'desenrugar'],
  '636': ['desavença', 'dissensão', 'dissentimento'],
  '637': [
    'bonança',
    'calma',
    'descanso',
    'paz',
    'placidez',
    'quietação',
    'quietude',
    'repouso',
    'serenidade',
    'sossego',
    'tranquilidade',
  ],
  '638': ['desconhecido', 'incógnito'],
  '639': ['descorado', 'lívido', 'macilento', 'pálido'],
  '640': [
    'desatencioso',
    'descortês',
    'grosseiro',
    'impolido',
    'impolítico',
    'incivil',
    'indelicado',
    'inurbano',
    'rústico',
    'tosco',
  ],
  '641': ['desculpa', 'escusa', 'perdão', 'recusa'],
  '642': ['desdizer-se', 'retratar-se'],
  '643': ['deserto', 'despovoado', 'ermo', 'solitário'],
  '644': ['deserto', 'ermo', 'soidão', 'soledade', 'solidão'],
  '645': ['desertor', 'trânsfuga'],
  '646': ['deserdar', 'exerdar'],
  '647': ['assinalar', 'designar', 'indicar', 'sinalar'],
  '648': ['desembaraçar', 'desimpedir', 'desobstruir'],
  '649': ['desnecessário', 'escusado', 'supérfluo'],
  '650': ['desapossar', 'despojar', 'esbulhar', 'espoliar', 'extorquir', 'privar'],
  '651': ['desquite', 'divórcio', 'repúdio'],
  '652': ['dessepulto', 'insepulto'],
  '653': ['desvanecer', 'dissipar'],
  '654': ['cessar', 'deter', 'interromper', 'parar', 'sobrestar', 'sustar'],
  '655': ['detritos', 'fezes', 'lia', 'resíduo', 'sedimento'],
  '656': ['dever', 'obrigação'],
  '657': ['devolver', 'restituir'],
  '658': ['demoníaco', 'diabólico', 'infernal', 'satânico'],
  '659': ['dialética', 'lógica'],
  '660': ['dialecto', 'idioma', 'linguagem', 'língua'],
  '661': ['diurno', 'diário', 'quotidiano'],
  '662': ['dicção', 'elocução', 'estilo', 'expressão', 'frase', 'palavra', 'termo', 'vocábulo', 'voz'],
  '663': ['dicionário', 'elucidário', 'glossário', 'léxico', 'vocabulário'],
  '664': ['diferença', 'dissemelhança', 'distinção'],
  '665': ['dificuldade', 'embaraço', 'empecilho', 'estorvo', 'impedimento', 'obstáculo'],
  '666': ['comprido', 'difuso', 'prolixo', 'proluxo'],
  '667': ['digressão', 'distração', 'divagação', 'diversão'],
  '668': ['cortar', 'despedaçar', 'dilacerar', 'espedaçar', 'golpear', 'lacerar', 'rasgar', 'retalhar'],
  '669': [
    'consumir',
    'desbaratar',
    'desperdiçar',
    'dilapidar',
    'dissipar',
    'esbanjar',
    'esperdiçar',
    'estragar',
    'gastar',
    'malbaratar',
    'prodigalizar',
  ],
  '670': ['dimanar', 'efluir', 'emanar', 'fluir', 'manar'],
  '671': ['direito', 'jurisprudência'],
  '672': ['direito', 'justiça'],
  '673': ['conduzir', 'dirigir', 'guiar', 'levar'],
  '674': ['critério', 'discernimento', 'juízo', 'tino'],
  '675': ['diserto', 'elegante', 'eloquente', 'facundo'],
  '676': ['caro', 'custoso', 'dispendioso'],
  '677': [
    'direito',
    'dispensa',
    'escusa',
    'exenção',
    'franquia',
    'imunidade',
    'isenção',
    'liberdade',
    'licença',
    'prerrogativa',
    'privilégio',
    'regalia',
  ],
  '678': ['derramar', 'difundir', 'disseminar', 'distribuir', 'espalhar', 'semear'],
  '679': ['conselho', 'ditame', 'opinião', 'parecer', 'voto'],
  '680': ['dividir', 'repartir'],
  '681': ['divisa', 'emblema', 'empresa', 'símbolo'],
  '682': [
    'brando',
    'doce',
    'docilidade',
    'dócil',
    'flexível',
    'macio',
    'manso',
    'meigo',
    'obediente',
    'obediência',
    'pacífico',
    'suave',
    'submisso',
    'tratável',
  ],
  '683': [
    'assistência',
    'demora',
    'detença',
    'domicílio',
    'estada',
    'estadia',
    'morada',
    'moradia',
    'parada',
    'permanência',
    'residência',
  ],
  '684': ['detentor', 'dono', 'proprietário', 'senhor'],
  '685': ['donzela', 'menina', 'moça', 'rapariga'],
  '686': [
    'culto',
    'douto',
    'erudito',
    'esclarecido',
    'ilustrado',
    'instructo',
    'instruído',
    'perito',
    'sabedor',
    'sapiente',
    'sábio',
    'versado',
  ],
  '687': ['duração', 'eternidade', 'tempo'],
  '688': ['ebulição', 'efervescência', 'fervor', 'fervura'],
  '689': [
    'aguardentado',
    'alcoolizado',
    'avinhado',
    'borracho',
    'bêbado',
    'ebrioso',
    'embebedado',
    'emborrachado',
    'embriagado',
    'encachaçado',
    'inebriado',
    'temulento',
    'ébrio',
  ],
  '690': ['catafalco', 'cenotáfio', 'eça'],
  '691': ['bucólica', 'idílio', 'pastoral', 'poesia pastoril', 'écloga'],
  '692': ['econômico', 'parcimonioso', 'parco', 'poupado'],
  '693': ['editor', 'edição', 'impressor', 'impressão'],
  '694': ['civilização', 'criação', 'educação', 'ilustração', 'instrução'],
  '695': ['efetuar', 'executar', 'fazer', 'realizar'],
  '696': ['cópia', 'efígie', 'fotografia', 'imagem', 'retrato'],
  '697': ['eleger', 'eleição', 'escolha', 'escolher', 'preferir', 'preferência'],
  '698': ['embaixador', 'encarregado de negócios', 'enviado', 'internúncio', 'legado', 'ministro', 'núncio'],
  '699': ['embrião', 'feto', 'gérmen', 'semente', 'sêmen'],
  '700': ['ardil', 'artifício', 'astúcia', 'embuste', 'estratagema', 'manha', 'mentira', 'patranha', 'peta'],
  '701': ['comodato', 'empréstimo', 'mutuação', 'mútuo'],
  '702': ['encarecer', 'exagerar'],
  '703': ['azo', 'conjunção', 'ensejo', 'ocasião', 'oportunidade'],
  '704': ['enterramento', 'enterro', 'exéquias', 'funeral', 'saimento'],
  '705': ['distrair', 'divertir', 'entreter', 'espairecer'],
  '706': ['despachar', 'enviar', 'expedir', 'mandar', 'remeter'],
  '707': ['desenlace', 'desfecho', 'epílogo', 'peroração'],
  '708': ['era', 'período', 'época'],
  '709': ['equidade', 'justiça', 'retidão'],
  '710': ['erário', 'fisco', 'tesouro'],
  '711': [
    'constituir',
    'construir',
    'erguer',
    'erigir',
    'estabelecer',
    'formar',
    'fundar',
    'instituir',
    'levantar',
    'organizar',
  ],
  '712': ['escapar', 'esquivar', 'evadir', 'evitar', 'fugir'],
  '713': [
    'carambina',
    'caramelo',
    'chuva de pedra',
    'escarcha',
    'geada',
    'gelo',
    'granizo',
    'neve',
    'pedrisco',
    'saraiva',
    'sincelos',
  ],
  '714': ['deslizar', 'escorregar', 'resvalar'],
  '715': ['escuro', 'obscuro', 'sombrio', 'tenebroso'],
  '716': ['atender', 'escutar', 'ouvir'],
  '717': ['esfaimado', 'esfomeado', 'faminto', 'famulento', 'femélico'],
  '718': ['cansado', 'esfalfado', 'extenuado', 'fatigado'],
  '719': [
    'alinho',
    'apuro',
    'asseio',
    'capricho',
    'correção',
    'cuidado',
    'esmero',
    'gosto',
    'limpeza',
    'primor',
    'requinte',
  ],
  '720': ['espantoso', 'horrendo', 'horroroso', 'horrível', 'terrificante', 'terrífico', 'terrível'],
  '721': ['especial', 'particular', 'privativo', 'singular'],
  '722': ['confiança', 'esperança', 'fé'],
  '723': ['atalaia', 'espia', 'espião', 'sentinela', 'vigia'],
  '724': ['espiar', 'espionar', 'espreitar'],
  '725': ['espontâneo', 'livre', 'voluntário'],
  '726': ['estado', 'nação', 'povo'],
  '727': ['contínuo', 'eterno', 'imortal', 'perpétuo'],
  '728': ['eumênides', 'fúrias'],
  '729': ['amaldiçoar', 'execrar', 'execração', 'imprecar', 'imprecação', 'maldizer', 'maldição', 'praga', 'praguejar'],
  '730': ['experiência', 'observação'],
  '731': ['fábrica', 'manufatura', 'oficina', 'tenda', 'usina'],
  '732': ['fachada', 'frente', 'frontaria', 'frontispício'],
  '733': ['faculdade', 'poder', 'potência'],
  '734': ['falecimento', 'morte', 'passamento', 'traspasse', 'trânsito'],
  '735': ['fanal', 'farol'],
  '736': ['enfadonho', 'fastidioso', 'importuno', 'tedioso'],
  '737': ['benigno', 'favorável', 'propício', 'próspero'],
  '738': ['favorito', 'mimo', 'mimoso', 'predileto', 'preferido', 'privado', 'valido'],
  '739': ['abundante', 'farto', 'fecundidade', 'fecundo', 'fertilidade', 'fértil', 'ubertoso', 'úbere'],
  '740': ['congratulações', 'cumprimentos', 'emboras', 'felicitações', 'parabéns', 'saudações'],
  '741': ['afortunado', 'ditoso', 'feliz', 'venturoso'],
  '742': ['ferramenta', 'instrumento', 'utensílios'],
  '743': ['defunto', 'finado', 'morto'],
  '744': ['fluido', 'líquido'],
  '745': ['franco', 'leal', 'sincero'],
  '746': ['dolo', 'doloso', 'fraude', 'fraudulento'],
  '747': ['frívolo', 'fútil'],
  '748': ['fuga', 'fugida'],
  '749': ['básico', 'capital', 'fundamental', 'principal'],
  '750': ['funeral', 'funerário', 'funéreo', 'fúnebre'],
  '751': ['cólera', 'enfurecido', 'furente', 'furial', 'furibundo', 'furioso', 'furor', 'fúria', 'ira', 'raiva'],
  '752': [
    'estelionato',
    'furtar',
    'furto',
    'ladroeira',
    'ladroíce',
    'latrocínio',
    'peculato',
    'plágio',
    'rapina',
    'rapinar',
    'raptar',
    'rapto',
    'roubar',
    'roubo',
  ],
  '753': ['futuro', 'porvindoiro', 'póstero', 'vindoiro'],
  '754': ['galardão', 'gratificação', 'prêmio', 'recompensa', 'comissão'],
  '755': ['charlar', 'cochichar', 'galrar', 'garlar', 'ou'],
  '756': ['ganho', 'ganância', 'interesse', 'lucro'],
  '757': ['abstração', 'generalização'],
  '758': ['generosidade', 'generoso', 'liberal', 'liberalidade', 'munificente', 'munificência'],
  '759': ['geral', 'universal'],
  '760': [
    'celebridade',
    'conceito',
    'crédito',
    'distinção',
    'fama',
    'glória',
    'honra',
    'lustre',
    'nomeada',
    'renome',
    'reputação',
  ],
  '761': ['gosto', 'gozo', 'paladar', 'ranço', 'ressaibo', 'sabor'],
  '762': ['gradação', 'graduação'],
  '763': ['dimensões', 'grandeza', 'grandura', 'magnitude', 'proporções', 'tamanho', 'volume'],
  '764': ['grandíssimo', 'muito grande'],
  '765': ['casa de campo', 'chácara', 'granja', 'quinta'],
  '766': ['gratidão', 'reconhecimento'],
  '767': ['guante', 'luva', 'manopla'],
  '768': ['escolta', 'guarda', 'patrulha', 'piquete', 'ronda'],
  '769': ['harmonia', 'harmonioso', 'harmônico'],
  '770': ['deixa', 'herança', 'hereditariedade', 'legado', 'sucessão'],
  '771': ['herói', 'representativo', 'super-homem'],
  '772': ['anais', 'epopeia', 'fastos', 'história', 'legenda', 'lenda', 'narrativa', 'narração', 'relação'],
  '773': ['historiador', 'historiógrafo'],
  '774': ['humildade', 'humilhação'],
  '775': ['ideal', 'imaginário'],
  '776': ['desonra', 'ignomínia', 'infâmia', 'opróbrio'],
  '777': ['acepipe', 'guloseima', 'iguaria', 'manjar', 'pitéu'],
  '778': ['imaginativa', 'imaginação', 'inventiva'],
  '779': ['imolar', 'imolação', 'sacrificar', 'sacrifício'],
  '780': ['impalpável', 'intangível', 'intáctil'],
  '781': ['imparcial', 'indiferente', 'neutral', 'neutro'],
  '782': ['improrrogável', 'inadiável', 'intransferível'],
  '783': ['inaptidão', 'incapacidade', 'insuficiência'],
  '784': ['ileso', 'incólume'],
  '785': ['inconstante', 'volúvel'],
  '786': ['incerteza', 'incerto', 'indeciso', 'indecisão', 'irresoluto', 'irresolução', 'perplexo'],
  '787': ['fixo', 'inalterável', 'inapagável', 'indelével'],
  '788': ['apatia', 'impassibilidade', 'indiferença', 'indolência', 'inexcitabilidade', 'insensibilidade'],
  '789': ['indivíduo', 'pessoa'],
  '790': ['indizível', 'inefável', 'inexprimível'],
  '791': ['infante', 'infantilidades', 'infância', 'meninice', 'meninices', 'puerilidades', 'puerícia'],
  '792': ['ascendente', 'ascendência', 'ação', 'influxo', 'influência', 'prestígio', 'superioridade'],
  '793': ['informação', 'inquérito', 'perquisição'],
  '794': ['encaixar', 'inserir', 'intercalar', 'interpor'],
  '795': ['insosso', 'insulso', 'insípido'],
  '796': ['desacostumado', 'desusado', 'insólito'],
  '797': ['instante', 'momento'],
  '798': ['insurgente', 'insurgido', 'insurrecionado', 'insurrecto', 'rebelado', 'rebelde', 'sublevado'],
  '799': ['interior', 'interno', 'intrínseco', 'íntimo'],
  '800': ['inválido', 'nulo', 'írrito'],
  '801': ['jamais', 'nunca'],
  '802': ['afirmação', 'jura', 'juramento', 'promessa', 'protesto'],
  '803': ['certame', 'justa', 'torneio'],
  '804': ['largueza', 'largura'],
  '805': ['legal', 'legítimo', 'lícito', 'permitido'],
  '806': ['brunir', 'limar', 'polir'],
  '807': ['filologia', 'filólogo', 'gramática', 'gramático', 'linguista', 'linguística'],
  '808': ['distante', 'longínquo', 'remoto'],
  '809': ['forjar', 'maquinar', 'tecer', 'tramar', 'urdir'],
  '810': ['fonte', 'manadeiro', 'manancial', 'nascente', 'nascença', 'origem'],
  '811': ['mar', 'oceano'],
  '812': ['mas', 'porém'],
  '813': ['cadeia', 'calabouço', 'enxovia', 'masmorra'],
  '814': ['maternal', 'materno', 'paternal', 'paterno'],
  '815': ['matinal', 'matutino'],
  '816': ['medicamento', 'remédio'],
  '817': ['lembrança', 'memória', 'recordação', 'reminiscência', 'retentiva'],
  '818': ['mendicidade', 'mendicância', 'mendigo'],
  '819': ['mercadoria', 'mercancia'],
  '820': ['ceifa', 'colheita', 'messe', 'seara'],
  '821': ['maravilha', 'milagre', 'prodígio'],
  '822': ['espiritual', 'espiritualidade', 'espiritualismo', 'misticidade', 'misticismo', 'místico'],
  '823': ['moda', 'uso', 'voga'],
  '824': ['idiotismo', 'modismo'],
  '825': ['monacal', 'monástico'],
  '826': ['monólogo', 'solilóquio'],
  '827': ['cerro', 'cerrote', 'colina', 'cordilheira', 'montanha', 'monte', 'outeiro', 'serra', 'serrania'],
  '828': ['montanheiro', 'montanhesco', 'montanhoso', 'montanhês', 'montano', 'montuoso'],
  '829': ['mundo', 'orbe', 'universo'],
  '830': ['mútuo', 'recíproco'],
  '831': ['dríade', 'napeia', 'ninfa', 'náiade', 'tágide'],
  '832': ['naval', 'náutico'],
  '833': ['conveniente', 'forçoso', 'indispensável', 'necessário', 'preciso', 'urgente', 'útil'],
  '834': ['nós outros', 'nós'],
  '835': ['manifesto', 'notório', 'público'],
  '836': ['novo', 'recente'],
  '837': ['oblata', 'oblação', 'oferenda', 'oferta'],
  '838': ['côncavo', 'oco', 'vazio', 'vácuo', 'vão'],
  '839': ['cancelar', 'cortar', 'elidir', 'eliminar', 'omitir', 'suprimir'],
  '840': ['escarcéu', 'marouço', 'onda', 'vaga', 'vagalhão'],
  '841': ['onzena', 'usura'],
  '842': ['escolha', 'escolher', 'optar', 'opção', 'preferir', 'preferência'],
  '843': ['outrem', 'outro'],
  '844': [
    'estipêndio',
    'honorários',
    'mensalidade',
    'ordenado',
    'paga',
    'pagamento',
    'remuneração',
    'retribuição',
    'salário',
    'soldada',
    'soldo',
    'vencimentos',
  ],
  '845': ['folha', 'lauda', 'página'],
  '846': ['palpável', 'perceptível', 'sensível', 'visível'],
  '847': ['paralogismo', 'sofisma'],
  '848': ['casal', 'junta', 'par', 'parelha'],
  '849': ['pena', 'saudade'],
  '850': ['percepção', 'sensação', 'sentimento'],
  '851': ['perpendicular', 'vertical'],
  '852': ['poeta', 'vate'],
  '853': ['poesia', 'poética'],
  '854': ['bispo', 'pontífice', 'prelado', 'sacerdote'],
  '855': ['pois que', 'pois', 'porque', 'que', 'qual'],
  '856': ['possuir', 'ter'],
  '857': ['posterior', 'seguinte', 'subsecutivo', 'subsequente', 'ulterior'],
  '858': ['axioma', 'postulado'],
  '859': ['perversidade', 'perversão', 'pravidade'],
  '860': [
    'exórdio',
    'introdução',
    'introito',
    'prefação',
    'prefácio',
    'preliminar',
    'prelúdio',
    'preâmbulo',
    'prolegômenos',
    'proêmio',
    'prólogo',
  ],
  '861': ['expressamente', 'formalmente', 'justamente', 'positivamente', 'precisamente'],
  '862': ['antecipado', 'precoce', 'prematuro', 'temporão'],
  '863': ['primeiro', 'primevo', 'primitivo', 'primário'],
  '864': ['profanação', 'sacrilégio'],
  '865': [
    'ascendência',
    'casa',
    'casta',
    'estirpe',
    'família',
    'genealogia',
    'geração',
    'linhagem',
    'progenitura',
    'progênie',
    'prosápia',
    'raça',
    'sangue',
  ],
  '866': ['mesmo', 'próprio'],
  '867': ['cabriola', 'pinote', 'pirueta', 'pulo', 'salto'],
  '868': ['número', 'quantia', 'quantidade', 'soma'],
  '869': ['fantasia', 'ilusão', 'quimera', 'utopia', 'visão'],
  '870': [
    'chispante',
    'cintilante',
    'coruscante',
    'faiscante',
    'flamante',
    'irradiador',
    'irradiante',
    'radiante',
    'radioso',
    'relampejante',
    'reluzente',
  ],
  '871': ['pegada', 'pisada', 'rasto', 'trilha', 'vestígio'],
  '872': ['real', 'realengo', 'reguengo', 'reiuno', 'régio'],
  '873': [
    'destaque',
    'evidência',
    'preeminente',
    'preeminência',
    'proeminente',
    'proeminência',
    'realce',
    'relevo',
    'ressalto',
    'saliência',
  ],
  '874': ['realidade', 'verdade'],
  '875': ['quitação', 'recibo'],
  '876': ['reaver', 'recobrar', 'recuperar', 'retomar'],
  '877': ['gerente', 'gerir', 'regedor', 'regente', 'reger'],
  '878': ['desforra', 'desforço', 'despique', 'represália', 'retaliação', 'vindicta', 'vingança'],
  '879': ['abdicação', 'paciência', 'passividade', 'renunciamento', 'resignação'],
  '880': ['repercutir', 'ressoar', 'retinir', 'retumbar'],
  '881': ['redarguir', 'replicar', 'retorquir', 'retrucar'],
  '882': ['inspiração', 'revelação'],
  '883': ['diário', 'itinerário', 'portulânio', 'roteiro'],
  '884': ['ciência', 'sabedoria'],
  '885': ['sacro', 'sagrado', 'santo'],
  '886': ['higiênico', 'sadio', 'salubre', 'salutar', 'são'],
  '887': ['sangrento', 'sanguento', 'sanguinolento'],
  '888': ['laical', 'leigo', 'secular'],
  '889': ['carruagem', 'coche', 'sege', 'trem', 'veículo'],
  '890': ['secretar', 'secreção', 'segregar', 'segregação'],
  '891': ['ato contínuo', 'de seguida', 'em seguida', 'imediatamente', 'logo após', 'seguidamente'],
  '892': ['servir de', 'servir para'],
  '893': ['reserva', 'segredo', 'sigilo'],
  '894': ['apito', 'assobio', 'sibilo', 'silvo'],
  '895': ['simpleza', 'simplicidade'],
  '896': ['sistema', 'teoria'],
  '897': ['social', 'sociável'],
  '898': ['soporativo', 'soporoso', 'soporífero', 'soporífico'],
  '899': ['cidadão', 'súbdito', 'vassalo'],
  '900': ['meio-dia', 'sul'],
  '901': ['soberano', 'sumo', 'supremo'],
  '902': ['caldo', 'suco', 'sumo'],
  '903': ['substituto', 'suplente'],
  '904': ['arroubo', 'rapto', 'surto', 'transporte', 'voo'],
  '905': ['cisma', 'desconfiança', 'receio', 'suspeita'],
  '906': ['implícito', 'subentendido', 'tácito'],
  '907': ['baiuca', 'bodega', 'espelunca', 'locanda', 'quiosque', 'taberna', 'tasca', 'taverna', 'venda'],
  '908': ['gago', 'tartamelo', 'tartamudo', 'tatibitate', 'tátaro'],
  '909': ['desconfiar', 'recear', 'suspeitar', 'temer'],
  '910': ['basílica', 'capela', 'ermida', 'igreja', 'igrejinha', 'igrejola', 'igrejário', 'igrejório', 'templo'],
  '911': ['campo', 'solo', 'terra', 'terreno'],
  '912': ['cútis', 'derme', 'epiderme', 'pele', 'tez'],
  '913': ['morno', 'tépido', 'tíbio'],
  '914': ['carimbo', 'marca', 'selo', 'sinete', 'timbre'],
  '915': ['beca', 'garnacha', 'paludamento', 'toga', 'trábea'],
  '916': ['tomo', 'volume'],
  '917': ['desonesto', 'impudico', 'obsceno', 'torpe'],
  '918': ['tradução', 'versão'],
  '919': ['gole', 'hausto', 'sorvo', 'trago'],
  '920': ['trajo', 'vestido', 'vestidura', 'vestimenta'],
  '921': ['tristeza', 'tristura'],
  '922': ['triunfal', 'triunfante'],
  '923': ['mutilar', 'truncar'],
  '924': ['casula', 'dalmática', 'tunicela', 'túnica'],
  '925': ['turno', 'vez'],
  '926': ['chaga', 'ferida', 'úlcera'],
  '927': ['singular', 'só', 'um', 'único'],
  '928': ['junção', 'união'],
  '929': ['pressa', 'urgência'],
  '930': ['conveniente', 'proveitoso', 'vantajoso', 'útil'],
  '931': ['baldado', 'improfícuo', 'inútil', 'vão'],
  '932': ['veracidade', 'veraz', 'verdade', 'verdadeiro', 'veridicidade', 'verídico'],
  '933': ['avenida', 'vial'],
  '934': ['barrote', 'trave', 'viga'],
  '935': ['homem', 'varonil', 'varão', 'viril'],
  '936': ['vital', 'vivaz', 'viável'],
  '937': ['vencedor', 'vitorioso'],
  '938': ['veleidade', 'volição', 'vontade'],
  '939': ['bombo', 'zabumba'],
  '940': ['alganame', 'pastor', 'pegureiro', 'zagal'],
  '941': ['estrábico', 'peto', 'vesgo', 'zanaga', 'zarolho'],
  '942': ['cortesia', 'mesura', 'rapapé', 'salamaleque', 'zumbaia'],
  '943': ['zum-zum', 'zumbido', 'zunido'],
  '944': ['tu', 'vc', 'você'],
  '945': ['é', 'e'],
  '946': ['Saudações', 'viva', 'fala', 'e ai', 'olá', 'iai', 'ea', 'eai', 'oi', 'opa'],
  '947': [
    'Amigo',
    'Companheiro',
    'Colega',
    'Aliado',
    'Parceiro',
    'Irmão',
    'Cúmplice',
    'Amistoso',
    'Afim',
    'Amiguinho',
    'Amiguinha',
    'Conhecido',
    'Contato',
    'Protetor',
    'Solidário',
    'Simpático',
    'Afinado',
    'Familiar',
    'Fraterno',
    'Unido',
    'Confiável',
    'Leal',
    'Generoso',
    'Benevolente',
    'Empático',
    'Compreensivo',
    'Apoiador',
    'Participante',
    'Entusiasta',
    'Amável.',
    'Bondoso',
    'Carinhoso',
    'Colaborador',
    'Cooperativo',
    'Apoiador',
    'Diplomático',
    'Tolerante',
    'Incondicional',
    'Benfeitor',
    'Acolhedor',
    'Cordial',
    'Preocupado',
    'Sincero',
    'Apaixonado',
    'Grato',
    'amiga',
    'amigo',
    'Generoso',
    'Empenhado',
    'Solidário',
    'Leal',
    'Amigável',
    'Protetor.',
  ],
};
